/*
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

/// <summary>
/// Provides Sales Invoice behavior and Credit Note transformation.
/// </summary>
public class SalesInvoiceDataModule: SalesDataModule
{
    // ● protected
    /// <summary>
    /// Validates that the current Sales Invoice can create a Credit Note.
    /// </summary>
    protected virtual void CheckCanCreateCreditNote()
    {
        if (CurrentRow == null)
            throw new TripousBusinessException("No Sales Invoice is selected.");
        if (HasChanges())
            throw new TripousBusinessException("Save or cancel the Sales Invoice changes before creating a Sales Credit Note.");
    }
    /// <summary>
    /// Validates that the current Sales Invoice can create a Cancellation document.
    /// </summary>
    protected virtual void CheckCanCreateCancellation()
    {
        if (CurrentRow == null)
            throw new TripousBusinessException("No Sales Invoice is selected.");
        if (HasChanges())
            throw new TripousBusinessException("Save or cancel the Sales Invoice changes before creating a Sales Cancellation.");
        if (HasCreditedQuantity())
            throw new TripousBusinessException("A Sales Invoice with posted Credit Notes cannot be cancelled.");
    }
    /// <summary>
    /// Validates that the current Sales Invoice can create a Customer Receipt.
    /// </summary>
    protected virtual void CheckCanCreateCustomerReceipt()
    {
        if (CurrentRow == null)
            throw new TripousBusinessException("No Sales Invoice is selected.");
        if (HasChanges())
            throw new TripousBusinessException("Save or cancel the Sales Invoice changes before creating a Customer Receipt.");
        if ((TradeStatus)CurrentRow.AsInteger("TradeStatusId") != TradeStatus.Posted)
            throw new TripousBusinessException("Only posted Sales Invoices can create Customer Receipts.");
        if (CurrentRow.AsBoolean("IsCancelled"))
            throw new TripousBusinessException("A cancelled Sales Invoice cannot create a Customer Receipt.");
    }
    /// <summary>
    /// Sets a row field only when the target column exists.
    /// </summary>
    protected virtual void SetValueIfColumnExists(DataRow Row, string FieldName, object Value)
    {
        if (Row != null && Row.Table.Columns.Contains(FieldName))
            Row.SetValue(FieldName, Value);
    }
    /// <summary>
    /// Sets Person locator display fields on a programmatically created payment.
    /// </summary>
    protected virtual void SetPersonDisplayFields(DataRow PaymentRow)
    {
        DataRow Person = Store.SelectResults("""
                                             select Code, Name
                                             from Person
                                             where Id = :Id
                                             """, new Dictionary<string, object>()
        {
            ["Id"] = CurrentRow.AsString("PersonId"),
        });
        if (Person == null)
            return;
        SetValueIfColumnExists(PaymentRow, "Person__Code", Person.AsString("Code"));
        SetValueIfColumnExists(PaymentRow, "Person__Name", Person.AsString("Name"));
    }
    /// <summary>
    /// Returns the posted finance movement generated by the current Sales Invoice.
    /// </summary>
    protected virtual DataRow GetInvoiceFinanceMovement()
    {
        return Store.SelectResults("""
                                   select *
                                   from FinanceMovement
                                   where SourceTable = 'Trade'
                                     and SourceId = :SourceId
                                     and PersonId = :PersonId
                                     and TradeTypeId = :TradeTypeId
                                   """, new Dictionary<string, object>()
        {
            ["SourceId"] = CurrentRow.AsString("Id"),
            ["PersonId"] = CurrentRow.AsString("PersonId"),
            ["TradeTypeId"] = (int)TradeType.Sales,
        });
    }
    /// <summary>
    /// Returns the already posted settlement amount against a finance movement.
    /// </summary>
    protected virtual decimal GetPostedSettlementAmount(string FinanceMovementId)
    {
        object Result = Store.SelectResult("""
                                           select sum(PaymentSettlement.Amount)
                                           from PaymentSettlement
                                             inner join Payment on Payment.Id = PaymentSettlement.PaymentId
                                           where PaymentSettlement.FinanceMovementId = :FinanceMovementId
                                             and Payment.StatusId = :StatusId
                                             and Payment.IsCancelled = 0
                                           """, null, new Dictionary<string, object>()
        {
            ["FinanceMovementId"] = FinanceMovementId,
            ["StatusId"] = (int)TradeStatus.Posted,
        });
        return Sys.IsNull(Result) ? 0 : RoundAmount(Convert.ToDecimal(Result));
    }
    /// <summary>
    /// Returns the current open amount of the invoice finance movement.
    /// </summary>
    protected virtual decimal GetOpenPaymentAmount(DataRow FinanceMovement)
    {
        if (FinanceMovement == null)
            return 0;
        return RoundAmount(FinanceMovement.AsDecimal("Amount") - GetPostedSettlementAmount(FinanceMovement.AsString("Id")));
    }
    protected override void TableSet_TransactionStageCommit(object sender, TransactionEventArgs e)
    {
        base.TableSet_TransactionStageCommit(sender, e);

        if (IsPosting && e.Stage == TransactionStage.Post && e.ExecTime == ExecTime.After)
            UpdateSourceTransformationQuantities(e.Transaction, "Sales Delivery Note", "InvoicedQuantity", "Invoice", "The Sales Invoice has no lines.");
    }

    // ● construction
    public SalesInvoiceDataModule()
    {
    }

    // ● public
    /// <summary>
    /// Creates an unsaved Sales Credit Note from the remaining invoice quantities.
    /// </summary>
    public virtual SalesCreditNoteDataModule CreateCreditNote()
    {
        CheckCanCreateCreditNote();
        SalesCreditNoteDataModule Result = CreateTransformedDocument("SalesCreditNote", "Sales Invoice", "CreditedQuantity") as SalesCreditNoteDataModule;
        if (Result == null)
            throw new TripousDataException("Cannot create a Sales Credit Note module.");
        return Result;
    }
    /// <summary>
    /// Creates an unsaved Sales Cancellation from the complete Invoice.
    /// </summary>
    public virtual SalesCancellationDataModule CreateCancellation()
    {
        CheckCanCreateCancellation();
        SalesCancellationDataModule Result = CreateTransformedDocument("SalesCancellation", "Sales Invoice", "CreditedQuantity") as SalesCancellationDataModule;
        if (Result == null)
            throw new TripousDataException("Cannot create a Sales Cancellation module.");
        Result.CurrentRow.SetValue("CancelsTradeId", CurrentRow["Id"]);
        return Result;
    }
    /// <summary>
    /// Creates an unsaved Customer Receipt for the open invoice amount.
    /// </summary>
    public virtual PaymentDataModule CreateCustomerReceipt()
    {
        CheckCanCreateCustomerReceipt();
        DataRow FinanceMovement = GetInvoiceFinanceMovement();
        decimal OpenAmount = GetOpenPaymentAmount(FinanceMovement);
        if (OpenAmount <= 0)
            throw new TripousBusinessException("The Sales Invoice has no open amount to receive.");
        PaymentDataModule Result = DataRegistry.CreateModule("CustomerReceipt") as PaymentDataModule;
        if (Result == null)
            throw new TripousDataException("Cannot create the Customer Receipt module.");
        Result.Insert();
        Result.CurrentRow.SetValue("PersonId", CurrentRow["PersonId"]);
        SetPersonDisplayFields(Result.CurrentRow);
        Result.CurrentRow.SetValue("CurrencyId", CurrentRow["CurrencyId"]);
        Result.CurrentRow.SetValue("ExchangeRate", CurrentRow["ExchangeRate"]);
        Result.CurrentRow.SetValue("Amount", OpenAmount);
        Result.CurrentRow.SetValue("ExternalRef", CurrentRow.AsString("Code"));
        MemTable SettlementTable = Result.GetTable("PaymentSettlement");
        DataRow SettlementRow = SettlementTable.AddNewRow();
        SettlementRow.SetValue("PaymentId", Result.CurrentRow["Id"]);
        SettlementRow.SetValue("FinanceMovementId", FinanceMovement["Id"]);
        SetValueIfColumnExists(SettlementRow, "FinanceMovement__DocumentCode", FinanceMovement.AsString("DocumentCode"));
        SettlementRow.SetValue("Amount", OpenAmount);
        Result.CurrentRow.SetValue("SettledAmount", OpenAmount);
        Result.CurrentRow.SetValue("UnappliedAmount", 0m);
        return Result;
    }
}
