using System.Text;

namespace TripousWebBundler;

/// <summary>
/// Bundles Tripous Web source fragments into runtime JavaScript or CSS files.
/// </summary>
internal static class Program
{
    // ● private
    static private readonly StringComparer fComparer = StringComparer.OrdinalIgnoreCase;
    static private readonly Encoding fEncoding = new UTF8Encoding(false);

    // ● private
    static private int Main(string[] args)
    {
        try
        {
            BundleOptions Options = BundleOptions.Parse(args);
            if (Options.ShowHelp)
            {
                WriteHelp();
                return 0;
            }

            Bundle(Options);
            return 0;
        }
        catch (Exception Ex)
        {
            Console.Error.WriteLine(Ex.Message);
            return 1;
        }
    }
    static private void Bundle(BundleOptions Options)
    {
        DirectoryInfo SourceFolder = new(Options.SourceFolder);
        DirectoryInfo OutputFolder = new(Options.OutputFolder);
        List<BundleGroup> Groups;

        if (!SourceFolder.Exists)
            throw new DirectoryNotFoundException($"Source folder not found: {SourceFolder.FullName}");

        Groups = GetGroups(SourceFolder, Options.Extension);

        if (Groups.Count == 0)
        {
            Console.WriteLine($"No .{Options.Extension} source files found in {SourceFolder.FullName}");
            return;
        }

        if (Options.DryRun)
        {
            WriteDryRun(OutputFolder, Groups);
            return;
        }

        OutputFolder.Create();

        if (Options.Clean)
            CleanOutputFolder(OutputFolder, Options.Extension);

        foreach (BundleGroup Group in Groups)
            WriteBundle(OutputFolder, Group);
    }
    static private List<BundleGroup> GetGroups(DirectoryInfo SourceFolder, string Extension)
    {
        List<BundleGroup> Result = [];

        foreach (DirectoryInfo Folder in SourceFolder.GetDirectories("*", SearchOption.TopDirectoryOnly).OrderBy(item => item.Name, fComparer))
        {
            List<FileInfo> Files = Folder.GetFiles($"*.{Extension}", SearchOption.TopDirectoryOnly).OrderBy(item => item.Name, fComparer).ToList();

            if (Files.Count == 0)
                continue;

            Files.Sort(CompareFiles);
            Result.Add(new BundleGroup(Folder.Name, GetOutputFileName(Folder.Name, Extension), Files));
        }

        return Result;
    }
    static private int CompareFiles(FileInfo A, FileInfo B)
    {
        int Result = GetFragmentOrder(A).CompareTo(GetFragmentOrder(B));
        return Result != 0 ? Result : string.Compare(A.Name, B.Name, StringComparison.OrdinalIgnoreCase);
    }
    static private int GetFragmentOrder(FileInfo File)
    {
        string Name = Path.GetFileNameWithoutExtension(File.Name);
        int DashIndex = Name.IndexOf('-', StringComparison.Ordinal);
        int Index;
        int Result = 0;

        if (Name.Length > 0 && char.IsDigit(Name[0]))
        {
            for (Index = 0; Index < Name.Length && char.IsDigit(Name[Index]); Index++)
                Result = (Result * 10) + (Name[Index] - '0');

            return Result;
        }

        if (DashIndex < 0 || DashIndex + 1 >= Name.Length || !char.IsDigit(Name[DashIndex + 1]))
            return int.MaxValue;

        for (Index = DashIndex + 1; Index < Name.Length && char.IsDigit(Name[Index]); Index++)
            Result = (Result * 10) + (Name[Index] - '0');

        return Result;
    }
    static private string GetOutputFileName(string BundleName, string Extension)
    {
        return $"{BundleName.Replace('_', '-')}.{Extension}";
    }
    static private void CleanOutputFolder(DirectoryInfo OutputFolder, string Extension)
    {
        foreach (FileInfo File in OutputFolder.GetFiles($"*.{Extension}", SearchOption.TopDirectoryOnly))
            File.Delete();
    }
    static private void WriteBundle(DirectoryInfo OutputFolder, BundleGroup Group)
    {
        FileInfo OutputFile = new(Path.Combine(OutputFolder.FullName, Group.OutputFileName));
        string Content = BuildBundleText(Group);
        string ExistingContent = OutputFile.Exists ? File.ReadAllText(OutputFile.FullName, fEncoding) : string.Empty;

        if (string.Equals(Content, ExistingContent, StringComparison.Ordinal))
        {
            Console.WriteLine($"Unchanged: {OutputFile.FullName}");
            return;
        }

        File.WriteAllText(OutputFile.FullName, Content, fEncoding);
        Console.WriteLine($"Written: {OutputFile.FullName}");
    }
    static private string BuildBundleText(BundleGroup Group)
    {
        StringBuilder Builder = new();

        Builder.AppendLine("/*");
        Builder.AppendLine(" * <auto-generated>");
        Builder.AppendLine(" * This file is generated by TripousWebBundler.");
        Builder.AppendLine(" * Do not edit this file directly. Edit the source fragments instead.");
        Builder.AppendLine(" * </auto-generated>");
        Builder.AppendLine(" */");

        foreach (FileInfo File in Group.Files)
        {
            Builder.AppendLine();
            Builder.AppendLine($"// ● {File.Name}");
            Builder.AppendLine(System.IO.File.ReadAllText(File.FullName, fEncoding).TrimEnd());
        }

        Builder.AppendLine();
        return Builder.ToString();
    }
    static private void WriteDryRun(DirectoryInfo OutputFolder, List<BundleGroup> Groups)
    {
        foreach (BundleGroup Group in Groups)
        {
            Console.WriteLine($"{Group.Name} -> {Path.Combine(OutputFolder.FullName, Group.OutputFileName)}");
            foreach (FileInfo File in Group.Files)
                Console.WriteLine($"  {File.Name}");
        }
    }
    static private void WriteHelp()
    {
        Console.WriteLine("TripousWebBundler");
        Console.WriteLine();
        Console.WriteLine("Arguments:");
        Console.WriteLine("  --source <folder>      Source root folder containing one subfolder per bundle.");
        Console.WriteLine("  --output <folder>      Output bundle folder.");
        Console.WriteLine("  --extension <js|css>   Source and output file extension.");
        Console.WriteLine("  --clean                Deletes existing output files for the extension before writing.");
        Console.WriteLine("  --dry-run              Prints detected bundles without writing files.");
        Console.WriteLine("  --help                 Shows help.");
        Console.WriteLine();
        Console.WriteLine("Convention:");
        Console.WriteLine("  js-src/tp/00-core.js       -> tp.js");
        Console.WriteLine("  js-src/tp-UI/00-core.js    -> tp-UI.js");
        Console.WriteLine("  js-src/tp-Data/00-core.js  -> tp-Data.js");
    }
}

/// <summary>
/// Command-line options for the Tripous Web bundler.
/// </summary>
internal sealed class BundleOptions
{
    // ● private
    static private readonly HashSet<string> fAllowedExtensions = new(StringComparer.OrdinalIgnoreCase) { "js", "css" };
    static private bool IsArg(string Value, params string[] Names)
    {
        return Names.Any(Name => string.Equals(Value, Name, StringComparison.OrdinalIgnoreCase));
    }
    static private string ReadValue(string[] args, ref int Index, string Arg)
    {
        if (Index + 1 >= args.Length)
            throw new InvalidOperationException($"Missing value for argument: {Arg}");

        Index++;
        return args[Index];
    }
    static private string NormalizeExtension(string Extension)
    {
        return Extension.Trim().TrimStart('.').ToLowerInvariant();
    }

    // ● constructor
    /// <summary>
    /// Creates a new options instance.
    /// </summary>
    public BundleOptions()
    {
    }

    // ● static public
    /// <summary>
    /// Parses command-line arguments.
    /// </summary>
    /// <param name="args">The command-line arguments.</param>
    /// <returns>Returns the parsed options.</returns>
    static public BundleOptions Parse(string[] args)
    {
        BundleOptions Result = new();

        for (int Index = 0; Index < args.Length; Index++)
        {
            string Arg = args[Index];

            if (IsArg(Arg, "--help", "-h", "/?"))
                Result.ShowHelp = true;
            else if (IsArg(Arg, "--source", "-s"))
                Result.SourceFolder = ReadValue(args, ref Index, Arg);
            else if (IsArg(Arg, "--output", "-o"))
                Result.OutputFolder = ReadValue(args, ref Index, Arg);
            else if (IsArg(Arg, "--extension", "-e"))
                Result.Extension = NormalizeExtension(ReadValue(args, ref Index, Arg));
            else if (IsArg(Arg, "--clean"))
                Result.Clean = true;
            else if (IsArg(Arg, "--dry-run"))
                Result.DryRun = true;
            else
                throw new InvalidOperationException($"Unknown argument: {Arg}");
        }

        if (!Result.ShowHelp)
            Result.Validate();

        return Result;
    }

    // ● public
    /// <summary>
    /// Validates this instance.
    /// </summary>
    public void Validate()
    {
        if (string.IsNullOrWhiteSpace(SourceFolder))
            throw new InvalidOperationException("Missing required argument: --source");
        if (string.IsNullOrWhiteSpace(OutputFolder))
            throw new InvalidOperationException("Missing required argument: --output");
        if (string.IsNullOrWhiteSpace(Extension))
            throw new InvalidOperationException("Missing required argument: --extension");
        if (!fAllowedExtensions.Contains(Extension))
            throw new InvalidOperationException($"Unsupported extension: {Extension}");
    }

    // ● properties
    /// <summary>
    /// Gets or sets the source folder.
    /// </summary>
    public string SourceFolder { get; set; } = string.Empty;
    /// <summary>
    /// Gets or sets the output folder.
    /// </summary>
    public string OutputFolder { get; set; } = string.Empty;
    /// <summary>
    /// Gets or sets the file extension to bundle.
    /// </summary>
    public string Extension { get; set; } = string.Empty;
    /// <summary>
    /// Gets or sets a value indicating whether existing output files should be deleted before writing.
    /// </summary>
    public bool Clean { get; set; }
    /// <summary>
    /// Gets or sets a value indicating whether the command should only print detected bundles.
    /// </summary>
    public bool DryRun { get; set; }
    /// <summary>
    /// Gets or sets a value indicating whether help should be printed.
    /// </summary>
    public bool ShowHelp { get; set; }
}

/// <summary>
/// Represents a source fragment group that produces a bundle.
/// </summary>
internal sealed class BundleGroup
{
    // ● constructor
    /// <summary>
    /// Creates a new group instance.
    /// </summary>
    /// <param name="Name">The bundle name.</param>
    /// <param name="OutputFileName">The output file name.</param>
    /// <param name="Files">The source files.</param>
    public BundleGroup(string Name, string OutputFileName, List<FileInfo> Files)
    {
        this.Name = Name;
        this.OutputFileName = OutputFileName;
        this.Files = Files;
    }

    // ● properties
    /// <summary>
    /// Gets the bundle name.
    /// </summary>
    public string Name { get; }
    /// <summary>
    /// Gets the output file name.
    /// </summary>
    public string OutputFileName { get; }
    /// <summary>
    /// Gets the source files.
    /// </summary>
    public List<FileInfo> Files { get; }
}
