<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <NoWarn>$(NoWarn);NU1510;NU1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DocumentationFile>bin\Debug\net10.0\Tripous.Desktop.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DocumentationFile>bin\Release\net10.0\Tripous.Desktop.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia" Version="12.0.4"/>
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4"/>
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4"/>
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4"/>
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.17">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images32\" />
    <Folder Include="Images16\" />
    <AvaloniaResource Include="Images32\**" />
    <AvaloniaResource Include="Images16\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tripous\Tripous.csproj" />
    <ProjectReference Include="..\Tripous.Data\Tripous.Data.csproj" />
    <ProjectReference Include="..\..\Avalonia.Controls.Extras\Avalonia.Controls.Extras\Avalonia.Controls.Extras.csproj" />
  </ItemGroup>

</Project>
