/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Desktop;

public partial class DesktopRegistryVersion1: RegistryVersion
{
    // ● construction
    public DesktopRegistryVersion1()
    {
    }

    // ● properties
    public override int VersionNumber { get; } = 1;
}