/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Desktop;

public partial class DesktopRegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterForms()
    {
        DesktopRegistry.AddOrUpdateForm("Account", TitleKey: "Account", Module: "Account", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("Asset", TitleKey: "Asset", Module: "Asset", Group: "Assets");
        DesktopRegistry.AddOrUpdateForm("CustomerReceipt", TitleKey: "CustomerReceipt", Module: "CustomerReceipt", ClassName: "CustomerReceiptForm", Group: "Finance");
        DesktopRegistry.AddOrUpdateForm("CustomerReceiptCancellation", TitleKey: "CustomerReceiptCancellation", Module: "CustomerReceiptCancellation", ClassName: "CustomerReceiptCancellationForm", Group: "Finance");
        DesktopRegistry.AddOrUpdateForm("DocumentType", TitleKey: "DocumentType", Module: "DocumentType", Group: "Documents");
        DesktopRegistry.AddOrUpdateForm("FinanceBalance", TitleKey: "FinanceBalance", Module: "FinanceBalance", Group: "Finance", IsReadOnly: true);
        DesktopRegistry.AddOrUpdateForm("FinanceMovement", TitleKey: "FinanceMovement", Module: "FinanceMovement", Group: "Finance", IsReadOnly: true);
        DesktopRegistry.AddOrUpdateForm("JournalEntry", TitleKey: "JournalEntry", Module: "JournalEntry", ClassName: "JournalEntryForm", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("PurchaseCancellation", TitleKey: "PurchaseCancellation", Module: "PurchaseCancellation", ClassName: "PurchaseCancellationForm", Group: "Purchases", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("PurchaseCreditNote", TitleKey: "PurchaseCreditNote", Module: "PurchaseCreditNote", ClassName: "PurchaseCreditNoteForm", Group: "Purchases", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("PurchaseDeliveryNote", TitleKey: "PurchaseDeliveryNote", Module: "PurchaseDeliveryNote", ClassName: "PurchaseDeliveryNoteForm", Group: "Purchases", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("PurchaseInvoice", TitleKey: "PurchaseInvoice", Module: "PurchaseInvoice", ClassName: "PurchaseInvoiceForm", Group: "Purchases", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("PurchaseOrder", TitleKey: "PurchaseOrder", Module: "PurchaseOrder", ClassName: "PurchaseOrderForm", Group: "Purchases", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("PurchaseReturn", TitleKey: "PurchaseReturn", Module: "PurchaseReturn", ClassName: "PurchaseReturnForm", Group: "Purchases", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("SalesCancellation", TitleKey: "SalesCancellation", Module: "SalesCancellation", ClassName: "SalesCancellationForm", Group: "Sales", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("SalesCreditNote", TitleKey: "SalesCreditNote", Module: "SalesCreditNote", ClassName: "SalesCreditNoteForm", Group: "Sales", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("SalesDeliveryNote", TitleKey: "SalesDeliveryNote", Module: "SalesDeliveryNote", ClassName: "SalesDeliveryNoteForm", Group: "Sales", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("SalesInvoice", TitleKey: "SalesInvoice", Module: "SalesInvoice", ClassName: "SalesInvoiceForm", Group: "Sales", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("SalesOrder", TitleKey: "SalesOrder", Module: "SalesOrder", ClassName: "SalesOrderForm", Group: "Sales", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("SalesReturn", TitleKey: "SalesReturn", Module: "SalesReturn", ClassName: "SalesReturnForm", Group: "Sales", ItemClassName: "TradeItemPage");
        DesktopRegistry.AddOrUpdateForm("StockBalance", TitleKey: "StockBalance", Module: "StockBalance", Group: "Inventory", IsReadOnly: true);
        DesktopRegistry.AddOrUpdateForm("StockCount", TitleKey: "StockCount", Module: "StockCount", ClassName: "StockCountForm", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("StockMovement", TitleKey: "StockMovement", Module: "StockMovement", Group: "Inventory", IsReadOnly: true);
        DesktopRegistry.AddOrUpdateForm("StockReservation", TitleKey: "StockReservation", Module: "StockReservation", Group: "Inventory", IsReadOnly: true);
        DesktopRegistry.AddOrUpdateForm("StockTrade", TitleKey: "StockTrade", Module: "StockTrade", ClassName: "StockTradeForm", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("SupplierPayment", TitleKey: "SupplierPayment", Module: "SupplierPayment", ClassName: "SupplierPaymentForm", Group: "Finance");
        DesktopRegistry.AddOrUpdateForm("SupplierPaymentCancellation", TitleKey: "SupplierPaymentCancellation", Module: "SupplierPaymentCancellation", ClassName: "SupplierPaymentCancellationForm", Group: "Finance");
    }
}