/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterLocators()
    {
        DataRegistry.AddOrUpdateLocator2("FinanceMovement", Source: "FinanceMovement", KeyField: "Id", FormName: "FinanceMovement", WebFormName: "FinanceMovement");
        DataRegistry.AddOrUpdateLocator2("JournalEntry", Source: "JournalEntry", KeyField: "Id", FormName: "JournalEntry", WebFormName: "JournalEntry");
        DataRegistry.AddOrUpdateLocator2("Payment", Source: "Payment", KeyField: "Id", FormName: "CustomerReceipt", WebFormName: "CustomerReceipt");
        DataRegistry.AddOrUpdateLocator2("PaymentSettlementFinanceMovement", Source: "FinanceMovement", KeyField: "Id", ClassName: "tERP.Data.PaymentSettlementFinanceMovementLocator", FormName: "FinanceMovement", WebFormName: "FinanceMovement");
        DataRegistry.AddOrUpdateLocator2("Person", Source: "Person", KeyField: "Id", FormName: "Person", WebFormName: "Person");
        DataRegistry.AddOrUpdateLocator2("Product", Source: "Product", KeyField: "Id", FormName: "Product", WebFormName: "Product");
        DataRegistry.AddOrUpdateLocator2("StockCount", Source: "StockCount", KeyField: "Id", FormName: "StockCount", WebFormName: "StockCount");
        DataRegistry.AddOrUpdateLocator2("StockMovement", Source: "StockMovement", KeyField: "Id", FormName: "StockMovement", WebFormName: "StockMovement");
        DataRegistry.AddOrUpdateLocator2("StockTrade", Source: "StockTrade", KeyField: "Id", FormName: "StockTrade", WebFormName: "StockTrade");
        DataRegistry.AddOrUpdateLocator2("Supplier", Source: "ProductSupplier", KeyField: "Id");
        DataRegistry.AddOrUpdateLocator2("Trade", Source: "Trade", KeyField: "Id", FormName: "SalesOrder", WebFormName: "SalesOrder");
        DataRegistry.AddOrUpdateLocator2("TradeLine", Source: "TradeLine", KeyField: "Id");
    }
}