/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion1: RegistryVersion
{
    // ● public
    public override void RegisterLocators()
    {
        DataRegistry.AddOrUpdateLocator("Customer", Source: "Person", KeyField: "Id", FormName: "Person", WebFormName: "Person");
        DataRegistry.AddOrUpdateLocator("Employee", Source: "Person", KeyField: "Id", FormName: "Person", WebFormName: "Person");
        DataRegistry.AddOrUpdateLocator("Manager", Source: "Person", KeyField: "Id", FormName: "Person", WebFormName: "Person");
        DataRegistry.AddOrUpdateLocator("Product", Source: "Product", KeyField: "Id", FormName: "Product", WebFormName: "Product");
        DataRegistry.AddOrUpdateLocator("Supplier", Source: "Person", KeyField: "Id", FormName: "Person", WebFormName: "Person");
    }
}