/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion1: RegistryVersion
{
    // ● public
    public override void RegisterLookups()
    {
        DataRegistry.AddOrUpdateLookupWithTableName("AssetCategory", "AssetCategory", FormName: "AssetCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("AssetDepreciationMethod", "AssetDepreciationMethod", FormName: "AssetDepreciationMethod");
        DataRegistry.AddOrUpdateLookupWithTableName("AssetLocation", "AssetLocation", FormName: "AssetLocation");
        DataRegistry.AddOrUpdateLookupWithTableName("Bank", "Bank", FormName: "Bank");
        DataRegistry.AddOrUpdateLookupWithTableName("Carrier", "Carrier", FormName: "Carrier");
        DataRegistry.AddOrUpdateLookupWithTableName("Category", "Category", FormName: "Category");
        DataRegistry.AddOrUpdateLookupWithTableName("Company", "Company", FormName: "Company");
        DataRegistry.AddOrUpdateLookupWithTableName("CompanyBranch", "CompanyBranch");
        DataRegistry.AddOrUpdateLookupWithTableName("ContactType", "ContactType", FormName: "ContactType");
        DataRegistry.AddOrUpdateLookupWithTableName("CostCenter", "CostCenter", FormName: "CostCenter");
        DataRegistry.AddOrUpdateLookupWithTableName("Country", "Country", FormName: "Country");
        DataRegistry.AddOrUpdateLookupWithTableName("Currency", "Currency", FormName: "Currency");
        DataRegistry.AddOrUpdateLookupWithTableName("CustomerCategory", "CustomerCategory", FormName: "CustomerCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("DiscountCategory", "DiscountCategory", FormName: "DiscountCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("ExpenseCategory", "ExpenseCategory", FormName: "ExpenseCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("Language", "Language", FormName: "Language");
        DataRegistry.AddOrUpdateLookupWithTableName("PaymentMethod", "PaymentMethod", FormName: "PaymentMethod");
        DataRegistry.AddOrUpdateLookupWithTableName("PaymentTerm", "PaymentTerm", FormName: "PaymentTerm");
        DataRegistry.AddOrUpdateLookupWithTableName("PersonRoleType", "PersonRoleType", FormName: "PersonRoleType");
        DataRegistry.AddOrUpdateLookupWithTableName("PriceListType", "PriceListType", FormName: "PriceListType");
        DataRegistry.AddOrUpdateLookupWithTableName("ProductAttributeGroup", "ProductAttributeGroup", FormName: "ProductAttributeGroup");
        DataRegistry.AddOrUpdateLookupWithTableName("ProductBrand", "ProductBrand", FormName: "ProductBrand");
        DataRegistry.AddOrUpdateLookupWithTableName("ProductDimension", "ProductDimension", FormName: "ProductDimension");
        DataRegistry.AddOrUpdateLookupWithTableName("ProductGroup", "ProductGroup", FormName: "ProductGroup");
        DataRegistry.AddOrUpdateLookupWithTableName("SalesPerson", "SalesPerson", FormName: "SalesPerson");
        DataRegistry.AddOrUpdateLookupWithTableName("SupplierCategory", "SupplierCategory", FormName: "SupplierCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("SYS_NUMBER_SERIES", "SYS_NUMBER_SERIES", FormName: "NumberSeries");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxCategory", "TaxCategory", FormName: "TaxCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxOffice", "TaxOffice", FormName: "TaxOffice");
        DataRegistry.AddOrUpdateLookupWithTableName("UnitOfMeasure", "UnitOfMeasure", FormName: "UnitOfMeasure");
        DataRegistry.AddOrUpdateLookupWithTableName("VatRate", "VatRate", FormName: "VatRate");
        DataRegistry.AddOrUpdateLookupWithTableName("Warehouse", "Warehouse", FormName: "Warehouse");
    }
}