/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterLookups()
    {
        DataRegistry.AddOrGetLookupWithTableName("Account", "Account", FormName: "Account");
        DataRegistry.AddOrGetLookupWithTableName("AppUser", "AppUser", FormName: "AppUser");
        DataRegistry.AddOrGetLookupWithTableName("AssetCategory", "AssetCategory", FormName: "AssetCategory");
        DataRegistry.AddOrGetLookupWithTableName("AssetDepreciationMethod", "AssetDepreciationMethod", FormName: "AssetDepreciationMethod");
        DataRegistry.AddOrGetLookupWithTableName("AssetLocation", "AssetLocation", FormName: "AssetLocation");
        DataRegistry.AddOrGetLookupWithTableName("CashAccount", "CashAccount", FormName: "CashAccount");
        DataRegistry.AddOrGetLookupWithTableName("CompanyBankAccount", "CompanyBankAccount");
        DataRegistry.AddOrGetLookupWithTableName("CompanyBranch", "CompanyBranch");
        DataRegistry.AddOrGetLookupWithTableName("CostCenter", "CostCenter", FormName: "CostCenter");
        DataRegistry.AddOrGetLookupWithTableName("Country", "Country", FormName: "Country");
        DataRegistry.AddOrGetLookupWithTableName("Currency", "Currency", FormName: "Currency");
        DataRegistry.AddOrGetLookupWithTableName("DocumentType", "DocumentType", FormName: "DocumentType");
        DataRegistry.AddOrGetLookupWithTableName("JournalEntry", "JournalEntry", FormName: "JournalEntry");
        DataRegistry.AddOrGetLookupWithClassName("ModuleName", "DocumentModuleLookupSource");
        DataRegistry.AddOrGetLookupWithTableName("PaymentMethod", "PaymentMethod", FormName: "PaymentMethod");
        DataRegistry.AddOrGetLookupWithTableName("PaymentTerm", "PaymentTerm", FormName: "PaymentTerm");
        DataRegistry.AddOrGetLookupWithTableName("Person", "Person", FormName: "Person");
        DataRegistry.AddOrGetLookupWithTableName("Project", "Project", FormName: "Project");
        DataRegistry.AddOrGetLookupWithTableName("SYS_NUMBER_SERIES", "SYS_NUMBER_SERIES", FormName: "NumberSeries");
        DataRegistry.AddOrGetLookupWithTableName("UnitOfMeasure", "UnitOfMeasure", FormName: "UnitOfMeasure");
        DataRegistry.AddOrGetLookupWithTableName("VatRate", "VatRate", FormName: "VatRate");
        DataRegistry.AddOrGetLookupWithTableName("Warehouse", "Warehouse", FormName: "Warehouse");
    }
}