/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion1: RegistryVersion
{
    // ● public
    public override void RegisterCodeProviders()
    {
        DataRegistry.AddOrUpdateCodeProvider("BillOfMaterial");
        DataRegistry.AddOrUpdateCodeProvider("CashAccount");
        DataRegistry.AddOrUpdateCodeProvider("Company");
        DataRegistry.AddOrUpdateCodeProvider("FixedAsset");
        DataRegistry.AddOrUpdateCodeProvider("PersonAddress");
        DataRegistry.AddOrUpdateCodeProvider("Product");
        DataRegistry.AddOrUpdateCodeProvider("Project");
        DataRegistry.AddOrUpdateCodeProvider("SalesPerson");
        DataRegistry.AddOrUpdateCodeProvider("Warehouse");
        DataRegistry.AddOrUpdateCodeProvider("WarehouseLocation");
    }
}