/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterCodeProviders()
    {
        DataRegistry.AddOrGetCodeProvider("Asset");
        DataRegistry.AddOrGetCodeProvider("DRAFT-JournalEntry");
        DataRegistry.AddOrGetCodeProvider("DRAFT-PurchaseCancellation");
        DataRegistry.AddOrGetCodeProvider("DRAFT-PurchaseCreditNote");
        DataRegistry.AddOrGetCodeProvider("DRAFT-PurchaseDeliveryNote");
        DataRegistry.AddOrGetCodeProvider("DRAFT-PurchaseInvoice");
        DataRegistry.AddOrGetCodeProvider("DRAFT-PurchaseOrder");
        DataRegistry.AddOrGetCodeProvider("DRAFT-PurchaseReturn");
        DataRegistry.AddOrGetCodeProvider("DRAFT-SalesCancellation");
        DataRegistry.AddOrGetCodeProvider("DRAFT-SalesCreditNote");
        DataRegistry.AddOrGetCodeProvider("DRAFT-SalesDeliveryNote");
        DataRegistry.AddOrGetCodeProvider("DRAFT-SalesInvoice");
        DataRegistry.AddOrGetCodeProvider("DRAFT-SalesOrder");
        DataRegistry.AddOrGetCodeProvider("DRAFT-SalesReturn");
        DataRegistry.AddOrGetCodeProvider("DRAFT-StockCount");
        DataRegistry.AddOrGetCodeProvider("DRAFT-StockTrade");
        DataRegistry.AddOrGetCodeProvider("JournalEntry");
        DataRegistry.AddOrGetCodeProvider("PurchaseCancellation");
        DataRegistry.AddOrGetCodeProvider("PurchaseCreditNote");
        DataRegistry.AddOrGetCodeProvider("PurchaseDeliveryNote");
        DataRegistry.AddOrGetCodeProvider("PurchaseInvoice");
        DataRegistry.AddOrGetCodeProvider("PurchaseOrder");
        DataRegistry.AddOrGetCodeProvider("PurchaseReturn");
        DataRegistry.AddOrGetCodeProvider("SalesCancellation");
        DataRegistry.AddOrGetCodeProvider("SalesCreditNote");
        DataRegistry.AddOrGetCodeProvider("SalesDeliveryNote");
        DataRegistry.AddOrGetCodeProvider("SalesInvoice");
        DataRegistry.AddOrGetCodeProvider("SalesOrder");
        DataRegistry.AddOrGetCodeProvider("SalesReturn");
        DataRegistry.AddOrGetCodeProvider("StockCount");
        DataRegistry.AddOrGetCodeProvider("StockTrade");
    }
}