/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterLookups()
    {
        DataRegistry.AddOrUpdateLookupWithTableName("Account", "Account", FormName: "Account");
        DataRegistry.AddOrUpdateLookupWithTableName("AssetCategory", "AssetCategory", FormName: "AssetCategory");
        DataRegistry.AddOrUpdateLookupWithTableName("AssetDepreciationMethod", "AssetDepreciationMethod", FormName: "AssetDepreciationMethod");
        DataRegistry.AddOrUpdateLookupWithTableName("AssetLocation", "AssetLocation", FormName: "AssetLocation");
        DataRegistry.AddOrUpdateLookupWithTableName("CashAccount", "CashAccount", FormName: "CashAccount");
        DataRegistry.AddOrUpdateLookupWithTableName("CompanyBankAccount", "CompanyBankAccount");
        DataRegistry.AddOrUpdateLookupWithTableName("CompanyBranch", "CompanyBranch");
        DataRegistry.AddOrUpdateLookupWithTableName("CostCenter", "CostCenter", FormName: "CostCenter");
        DataRegistry.AddOrUpdateLookupWithTableName("Country", "Country", FormName: "Country");
        DataRegistry.AddOrUpdateLookupWithTableName("Currency", "Currency", FormName: "Currency");
        DataRegistry.AddOrUpdateLookupWithTableName("DocumentType", "DocumentType", FormName: "DocumentType");
        DataRegistry.AddOrUpdateLookupWithTableName("JournalEntry", "JournalEntry", FormName: "JournalEntry");
        DataRegistry.AddOrUpdateLookupWithClassName("ModuleName", "DocumentModuleLookupSource");
        DataRegistry.AddOrUpdateLookupWithTableName("PaymentMethod", "PaymentMethod", FormName: "PaymentMethod");
        DataRegistry.AddOrUpdateLookupWithTableName("PaymentTerm", "PaymentTerm", FormName: "PaymentTerm");
        DataRegistry.AddOrUpdateLookupWithTableName("Person", "Person", FormName: "Person");
        DataRegistry.AddOrUpdateLookupWithTableName("Project", "Project", FormName: "Project");
        DataRegistry.AddOrUpdateLookupWithTableName("SYS_APP_USER", "SYS_APP_USER", FormName: "AppUser");
        DataRegistry.AddOrUpdateLookupWithTableName("SYS_NUMBER_SERIES", "SYS_NUMBER_SERIES", FormName: "NumberSeries");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxBusinessGroup", "TaxBusinessGroup", FormName: "TaxBusinessGroup");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxClause", "TaxClause", FormName: "TaxClause");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxJurisdiction", "TaxJurisdiction", FormName: "TaxJurisdiction");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxProductGroup", "TaxProductGroup", FormName: "TaxProductGroup");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxRate", "TaxRate", FormName: "TaxRate");
        DataRegistry.AddOrUpdateLookupWithTableName("TaxRule", "TaxRule", FormName: "TaxRule");
        DataRegistry.AddOrUpdateLookupWithTableName("UnitOfMeasure", "UnitOfMeasure", FormName: "UnitOfMeasure");
        DataRegistry.AddOrUpdateLookupWithTableName("Warehouse", "Warehouse", FormName: "Warehouse");
    }
}