/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterLocators()
    {
        DataRegistry.AddOrGetLocator("JournalEntry", "JournalEntry", "Id", FormName: "JournalEntry");
        DataRegistry.AddOrGetLocator("Person", "Person", "Id", FormName: "Person");
        DataRegistry.AddOrGetLocator("Product", "Product", "Id", FormName: "Product");
        DataRegistry.AddOrGetLocator("StockCount", "StockCount", "Id", FormName: "StockCount");
        DataRegistry.AddOrGetLocator("StockTrade", "StockTrade", "Id", FormName: "StockTrade");
        DataRegistry.AddOrGetLocator("Supplier", "ProductSupplier", "Id");
        DataRegistry.AddOrGetLocator("Trade", "Trade", "Id", FormName: "SalesOrder");
        DataRegistry.AddOrGetLocator("TradeLine", "TradeLine", "Id");
    }
}