/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion1: RegistryVersion
{
    // ● public
    public override void RegisterCodeProviders()
    {
        DataRegistry.AddOrGetCodeProvider("BillOfMaterial");
        DataRegistry.AddOrGetCodeProvider("CashAccount");
        DataRegistry.AddOrGetCodeProvider("Company");
        DataRegistry.AddOrGetCodeProvider("FixedAsset");
        DataRegistry.AddOrGetCodeProvider("PersonAddress");
        DataRegistry.AddOrGetCodeProvider("Product");
        DataRegistry.AddOrGetCodeProvider("Project");
        DataRegistry.AddOrGetCodeProvider("SalesPerson");
        DataRegistry.AddOrGetCodeProvider("Warehouse");
        DataRegistry.AddOrGetCodeProvider("WarehouseLocation");
    }
}