/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion1: RegistryVersion
{
    // ● public
    public override void RegisterLocators()
    {
        DataRegistry.AddOrUpdateLocator("Customer", "Person", "Id", FormName: "Person");
        DataRegistry.AddOrUpdateLocator("Employee", "Person", "Id", FormName: "Person");
        DataRegistry.AddOrUpdateLocator("Manager", "Person", "Id", FormName: "Person");
        DataRegistry.AddOrUpdateLocator("Product", "Product", "Id", FormName: "Product");
        DataRegistry.AddOrUpdateLocator("Supplier", "Person", "Id", FormName: "Person");
    }
}