/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion2: RegistryVersion
{
    // ● public
    public override void RegisterCodeProviders()
    {
        DataRegistry.AddOrUpdateCodeProvider("Asset");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-JournalEntry");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-PurchaseCancellation");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-PurchaseCreditNote");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-PurchaseDeliveryNote");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-PurchaseInvoice");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-PurchaseOrder");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-PurchaseReturn");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-SalesCancellation");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-SalesCreditNote");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-SalesDeliveryNote");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-SalesInvoice");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-SalesOrder");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-SalesReturn");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-StockCount");
        DataRegistry.AddOrUpdateCodeProvider("DRAFT-StockTrade");
        DataRegistry.AddOrUpdateCodeProvider("JournalEntry");
        DataRegistry.AddOrUpdateCodeProvider("PurchaseCancellation");
        DataRegistry.AddOrUpdateCodeProvider("PurchaseCreditNote");
        DataRegistry.AddOrUpdateCodeProvider("PurchaseDeliveryNote");
        DataRegistry.AddOrUpdateCodeProvider("PurchaseInvoice");
        DataRegistry.AddOrUpdateCodeProvider("PurchaseOrder");
        DataRegistry.AddOrUpdateCodeProvider("PurchaseReturn");
        DataRegistry.AddOrUpdateCodeProvider("SalesCancellation");
        DataRegistry.AddOrUpdateCodeProvider("SalesCreditNote");
        DataRegistry.AddOrUpdateCodeProvider("SalesDeliveryNote");
        DataRegistry.AddOrUpdateCodeProvider("SalesInvoice");
        DataRegistry.AddOrUpdateCodeProvider("SalesOrder");
        DataRegistry.AddOrUpdateCodeProvider("SalesReturn");
        DataRegistry.AddOrUpdateCodeProvider("StockCount");
        DataRegistry.AddOrUpdateCodeProvider("StockTrade");
    }
}