/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class RegistryVersion1: RegistryVersion
{
    // ● public
    public override void RegisterForms()
    {
        DesktopRegistry.AddOrUpdateForm("AppUser", TitleKey: "AppUser", Module: "AppUser", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("AssetCategory", TitleKey: "AssetCategory", Module: "AssetCategory", Group: "Assets");
        DesktopRegistry.AddOrUpdateForm("AssetDepreciationMethod", TitleKey: "AssetDepreciationMethod", Module: "AssetDepreciationMethod", Group: "Assets");
        DesktopRegistry.AddOrUpdateForm("AssetLocation", TitleKey: "AssetLocation", Module: "AssetLocation", Group: "Assets");
        DesktopRegistry.AddOrUpdateForm("Bank", TitleKey: "Bank", Module: "Bank", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("Carrier", TitleKey: "Carrier", Module: "Carrier", Group: "Purchases");
        DesktopRegistry.AddOrUpdateForm("CashAccount", TitleKey: "CashAccount", Module: "CashAccount", Group: "Finance");
        DesktopRegistry.AddOrUpdateForm("Category", TitleKey: "Category", Module: "Category", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("Company", TitleKey: "Company", Module: "Company", Group: "Company");
        DesktopRegistry.AddOrUpdateForm("ContactType", TitleKey: "ContactType", Module: "ContactType", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("CostCenter", TitleKey: "CostCenter", Module: "CostCenter", Group: "Company");
        DesktopRegistry.AddOrUpdateForm("Country", TitleKey: "Country", Module: "Country", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("Currency", TitleKey: "Currency", Module: "Currency", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("CustomerCategory", TitleKey: "CustomerCategory", Module: "CustomerCategory", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("DiscountCategory", TitleKey: "DiscountCategory", Module: "DiscountCategory", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("ExpenseCategory", TitleKey: "ExpenseCategory", Module: "ExpenseCategory", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("FiscalYear", TitleKey: "FiscalYear", Module: "FiscalYear", Group: "Company");
        DesktopRegistry.AddOrUpdateForm("FixedAsset", TitleKey: "FixedAsset", Module: "FixedAsset", Group: "Assets");
        DesktopRegistry.AddOrUpdateForm("Language", TitleKey: "Language", Module: "Language", Group: "System");
        DesktopRegistry.AddOrUpdateForm("Log", TitleKey: "Log", Module: "Log", Group: "System", IsReadOnly: true);
        DesktopRegistry.AddOrUpdateForm("NumberSeries", TitleKey: "NumberSeries", Module: "NumberSeries", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("PaymentMethod", TitleKey: "PaymentMethod", Module: "PaymentMethod", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("PaymentTerm", TitleKey: "PaymentTerm", Module: "PaymentTerm", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("Person", TitleKey: "Person", Module: "Person", Group: "People");
        DesktopRegistry.AddOrUpdateForm("PersonRoleType", TitleKey: "PersonRoleType", Module: "PersonRoleType", Group: "People");
        DesktopRegistry.AddOrUpdateForm("PriceList", TitleKey: "PriceList", Module: "PriceList", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("PriceListType", TitleKey: "PriceListType", Module: "PriceListType", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("Product", TitleKey: "Product", Module: "Product", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("ProductAttributeGroup", TitleKey: "ProductAttributeGroup", Module: "ProductAttributeGroup", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("ProductBrand", TitleKey: "ProductBrand", Module: "ProductBrand", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("ProductDimension", TitleKey: "ProductDimension", Module: "ProductDimension", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("ProductGroup", TitleKey: "ProductGroup", Module: "ProductGroup", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("Project", TitleKey: "Project", Module: "Project", Group: "Projects");
        DesktopRegistry.AddOrUpdateForm("ResourceStrings", TitleKey: "ResourceStrings", Module: "ResourceStrings", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("SalesPerson", TitleKey: "SalesPerson", Module: "SalesPerson", Group: "Sales");
        DesktopRegistry.AddOrUpdateForm("StockReason", TitleKey: "StockReason", Module: "StockReason", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("SupplierCategory", TitleKey: "SupplierCategory", Module: "SupplierCategory", Group: "Purchases");
        DesktopRegistry.AddOrUpdateForm("SysConfig", TitleKey: "SysConfig", Module: "SysConfig", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("TaxBusinessGroup", TitleKey: "TaxBusinessGroup", Module: "TaxBusinessGroup", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("TaxClause", TitleKey: "TaxClause", Module: "TaxClause", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("TaxJurisdiction", TitleKey: "TaxJurisdiction", Module: "TaxJurisdiction", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("TaxOffice", TitleKey: "TaxOffice", Module: "TaxOffice", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("TaxProductGroup", TitleKey: "TaxProductGroup", Module: "TaxProductGroup", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("TaxRate", TitleKey: "TaxRate", Module: "TaxRate", Group: "Setup");
        DesktopRegistry.AddOrUpdateForm("TaxRule", TitleKey: "TaxRule", Module: "TaxRule", Group: "Accounting");
        DesktopRegistry.AddOrUpdateForm("UnitOfMeasure", TitleKey: "UnitOfMeasure", Module: "UnitOfMeasure", Group: "Inventory");
        DesktopRegistry.AddOrUpdateForm("Warehouse", TitleKey: "Warehouse", Module: "Warehouse", Group: "Inventory");
    }
}