/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class SchemaVersion2: SchemaVersionDef
{
    // ● private
    void RegisterTable_DocumentType()
    {
        string TableName = "DocumentType";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,

    TradeTypeId int @NOT_NULL,                         -- Enum TradeType

    NumberSeriesId @NVARCHAR(40) @NOT_NULL,            -- Lookup
    ModuleName @NVARCHAR(96) @NOT_NULL,                -- Lookup ModuleName ClassName:DocumentModuleLookupSource -- Module Name 

    IsActive @BOOL default 1 @NOT_NULL,
    IsSystem @BOOL default 0 @NOT_NULL,                -- system defined and protected type
    AllowManualNumber @BOOL default 0 @NOT_NULL,
    AutoComplete @BOOL default 0 @NOT_NULL,

    AffectsStock @BOOL default 0 @NOT_NULL,            -- Group Posting
    AffectsFinancial @BOOL default 0 @NOT_NULL,        -- Group Posting
    AffectsAccounting @BOOL default 0 @NOT_NULL,       -- Group Posting

    StockDirection int default 0 @NOT_NULL,            -- Group Posting
    FinancialDirection int default 0 @NOT_NULL,        -- Group Posting
    AccountingDirection int default 0 @NOT_NULL,       -- Group Posting

    IsCancellation @BOOL default 0 @NOT_NULL,          -- Group Cancellation
    CancellationTargetId @NVARCHAR(40) @NULL,          -- Lookup; Group Cancellation -- what document type may cancel

    PrintTemplate @NVARCHAR(96) @NULL,                 -- Group Output
    ReportName @NVARCHAR(96) @NULL,                    -- Group Output

    DisplayOrder int default 0 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,                         -- Group Appearance -- ui display color
    IconName @NVARCHAR(96) @NULL,                      -- Group Appearance -- ui icon

    Remarks @NBLOB_TEXT @NULL,                         -- LargeMemo; Group Notes

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (NumberSeriesId) REFERENCES SYS_NUMBER_SERIES(Id),
    FOREIGN KEY (CancellationTargetId) REFERENCES DocumentType(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockReservation()
    {
        string TableName = "StockReservation";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    ProductId @NVARCHAR(40) @NOT_NULL,                  -- Locator Product
    WarehouseId @NVARCHAR(40) @NOT_NULL,                -- Lookup

    ReservedQuantity @DECIMAL DEFAULT 0 @NOT_NULL,
    ExecutedQuantity @DECIMAL DEFAULT 0 @NOT_NULL,

    SourceModule @NVARCHAR(96) @NOT_NULL,
    SourceTable @NVARCHAR(96) @NOT_NULL,
    SourceId @NVARCHAR(40) @NOT_NULL,
    SourceLineId @NVARCHAR(40) @NOT_NULL,

    CreatedAt @DATE_TIME @NOT_NULL,

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),

    CONSTRAINT UQ_{TableName}_SourceLine UNIQUE (SourceLineId)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Account()
    {
        string TableName = "Account";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,

    ParentAccountId @NVARCHAR(40) @NULL,              -- Lookup Account

    AccountTypeId int @NOT_NULL,                      -- Enum AccountType
    NormalBalanceId int @NOT_NULL,                    -- Enum NormalBalance

    IsPosting @BOOL DEFAULT 1 @NOT_NULL,
    IsActive @BOOL DEFAULT 1 @NOT_NULL,

    Remarks @NBLOB_TEXT @NULL,                        -- LargeMemo

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (ParentAccountId) REFERENCES Account(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Asset()
    {
        string TableName = "Asset";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    Code @NVARCHAR(40) @NOT_NULL,                  -- Code AST-XXXXXX Asset
    Name @NVARCHAR(96) @NOT_NULL,

    AssetCategoryId @NVARCHAR(40) @NOT_NULL,       -- Lookup; Group Classification
    AssetLocationId @NVARCHAR(40) @NULL,           -- Lookup; Group Classification

    StatusId int DEFAULT 1 @NOT_NULL,              -- Enum AssetStatus

    AcquisitionDate @DATE @NOT_NULL,               -- Group Acquisition
    InServiceDate @DATE @NULL,                     -- Group Acquisition

    AcquisitionCost @DECIMAL @NOT_NULL,            -- Group Acquisition

    DepreciationMethodId @NVARCHAR(40) @NOT_NULL,  -- Lookup; Group Depreciation
    UsefulLifeMonths int @NOT_NULL,                -- Group Depreciation
    SalvageValue @DECIMAL DEFAULT 0 @NOT_NULL,     -- Group Depreciation

    AccumulatedDepreciation @DECIMAL DEFAULT 0 @NOT_NULL, -- Group Depreciation
    BookValue @DECIMAL DEFAULT 0 @NOT_NULL,        -- Group Depreciation

    SerialNumber @NVARCHAR(96) @NULL,              -- Group Classification

    SupplierId @NVARCHAR(40) @NULL,                -- Locator Supplier; Group Supplier

    Remarks @NBLOB_TEXT @NULL,                     -- LargeMemo; Group Notes

    CreatedAt @DATE_TIME @NOT_NULL,                -- Group Audit
    CreatedBy @NVARCHAR(40) @NOT_NULL,             --  Lookup SYS_APP_USER; Group Audit
    ModifiedAt @DATE_TIME @NULL,                   -- Group Audit
    ModifiedBy @NVARCHAR(40) @NULL,                --  Lookup SYS_APP_USER; Group Audit

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),

    FOREIGN KEY (AssetCategoryId) REFERENCES AssetCategory(Id),
    FOREIGN KEY (AssetLocationId) REFERENCES AssetLocation(Id),
    FOREIGN KEY (DepreciationMethodId) REFERENCES AssetDepreciationMethod(Id),
    FOREIGN KEY (SupplierId) REFERENCES ProductSupplier(Id),
    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (ModifiedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Trade()
    {
        string TableName = "Trade";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,             

    DocumentTypeId @NVARCHAR(40) @NOT_NULL,             -- Lookup; [Hidden]
    Code @NVARCHAR(40) @NOT_NULL,                       -- Code; [ReadOnlyUI]
    TradeTypeId int default 0 @NOT_NULL,                -- [Hidden]

    TradeStatusId int default 1 @NOT_NULL,              -- Enum TradeStatus; [ReadOnlyUI]
    TaxBusinessGroupId @NVARCHAR(40) @NULL,             -- Lookup -- Tax classification copied from Person and stored as a document snapshot
    OriginTaxJurisdictionId @NVARCHAR(40) @NULL,        -- Lookup -- Jurisdiction resolved from the company or branch address
    DestinationTaxJurisdictionId @NVARCHAR(40) @NULL,   -- Lookup -- Jurisdiction resolved from the transaction address or selected as an override

    TradeDate @DATE @NOT_NULL,                          -- 
    PostingDate @DATE @NULL,                            -- [ReadOnlyUI]
    DeliveryDate @DATE @NULL,                           -- 
    DueDate @DATE @NULL,                                -- 

    ExternalRef @NVARCHAR(96) @NULL,                    -- e.g. ""Related to Order 123"", ""Your ref: PO-456""

    PersonId @NVARCHAR(40) @NOT_NULL,                   -- Locator Person -- Customer, Supplier, etc
    WarehouseId @NVARCHAR(40) @NULL,                    -- Lookup

    SalesPersonId @NVARCHAR(40) @NULL,                  -- Lookup Person; Group Organization
    ProjectId @NVARCHAR(40) @NULL,                      -- Lookup; Group Organization
    CostCenterId @NVARCHAR(40) @NULL,                   -- Lookup; Group Organization
    BranchId @NVARCHAR(40) @NULL,                       -- Lookup; Group Organization

    PriceListTypeId @NVARCHAR(40) @NULL,                -- Lookup -- Price list type stored as a document snapshot
    CurrencyId @NVARCHAR(40) @NOT_NULL,                 -- Lookup
    ExchangeRate @DECIMAL default 1 @NOT_NULL,          -- Exchange Rate for base currency

    PaymentMethodId @NVARCHAR(40) @NULL,                -- Lookup
    PaymentTermId @NVARCHAR(40) @NULL,                  -- Lookup

    BillingName @NVARCHAR(96) @NULL,                    -- Group Billing
    BillingAddressLine1 @NVARCHAR(128) @NULL,           -- Group Billing
    BillingAddressLine2 @NVARCHAR(128) @NULL,           -- Group Billing
    BillingCity @NVARCHAR(64) @NULL,                    -- Group Billing
    BillingRegion @NVARCHAR(64) @NULL,                  -- Group Billing -- State, province, or administrative region
    BillingPostalCode @NVARCHAR(20) @NULL,              -- Group Billing
    BillingCountryId @NVARCHAR(40) @NULL,               -- Lookup; Group Billing

    ShippingName @NVARCHAR(96) @NULL,                   -- Group Shipping
    ShippingAddressLine1 @NVARCHAR(128) @NULL,          -- Group Shipping
    ShippingAddressLine2 @NVARCHAR(128) @NULL,          -- Group Shipping
    ShippingCity @NVARCHAR(64) @NULL,                   -- Group Shipping
    ShippingRegion @NVARCHAR(64) @NULL,                 -- Group Shipping -- State, province, or administrative region
    ShippingPostalCode @NVARCHAR(20) @NULL,             -- Group Shipping
    ShippingCountryId @NVARCHAR(40) @NULL,              -- Lookup; Group Shipping

    SourceId @NVARCHAR(40) @NULL,                       -- Locator Trade; [Hidden]
    CancelsTradeId @NVARCHAR(40) @NULL,                 -- Locator Trade; [Hidden]
    CancelledByTradeId @NVARCHAR(40) @NULL,             -- Locator Trade; [Hidden]

    LinesAmount @DECIMAL default 0 @NOT_NULL,           -- Group Amounts; [ReadOnlyUI] -- sum of lines before header discounts/charges/taxes
    DiscountPercent @DECIMAL default 0 @NOT_NULL,       -- Group Amounts -- Header Discount %
    DiscountAmount @DECIMAL default 0 @NOT_NULL,        -- Group Amounts
    DiscountReason @NVARCHAR(256) @NULL,                -- Group Amounts

    ChargesAmount @DECIMAL default 0 @NOT_NULL,         -- Group Amounts

    NetAmount @DECIMAL default 0 @NOT_NULL,             -- Group Amounts; [ReadOnlyUI] -- = LinesAmount - DiscountAmount + ChargesAmount
    TaxAmount @DECIMAL default 0 @NOT_NULL,             -- Group Amounts; [ReadOnlyUI] -- Total tax amount from all line tax components
    TotalAmount @DECIMAL default 0 @NOT_NULL,           -- Group Amounts; [ReadOnlyUI]

    IsLocked @BOOL default 0 @NOT_NULL,                 -- [ReadOnlyUI] -- Lock document from editing
    IsCancelled @BOOL default 0 @NOT_NULL,              -- [ReadOnlyUI]

    CreatedAt @DATE_TIME @NOT_NULL,                     -- Group Audit; [ReadOnlyUI]
    CreatedBy @NVARCHAR(40) @NOT_NULL,                  --  Lookup SYS_APP_USER; Group Audit; [ReadOnlyUI]
    ModifiedAt @DATE_TIME @NULL,                        -- Group Audit; [ReadOnlyUI]
    ModifiedBy @NVARCHAR(40) @NULL,                     --  Lookup SYS_APP_USER; Group Audit; [ReadOnlyUI]
    PostedAt @DATE_TIME @NULL,                          -- Group Audit; [ReadOnlyUI]
    PostedBy @NVARCHAR(40) @NULL,                       --  Lookup SYS_APP_USER; Group Audit; [ReadOnlyUI]
    CancelledAt @DATE_TIME @NULL,                       -- Group Audit; [ReadOnlyUI]
    CancelledBy @NVARCHAR(40) @NULL,                    --  Lookup SYS_APP_USER; Group Audit; [ReadOnlyUI]

    Remarks @NVARCHAR(512) @NULL,                       -- Memo; Group Notes -- internal
    Comments @NVARCHAR(512) @NULL,                      -- Memo; Group Notes -- customer visible

    CONSTRAINT UQ_{TableName}_DocumentType_Code UNIQUE (DocumentTypeId, Code),

    FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),

    FOREIGN KEY (PersonId) REFERENCES Person(Id),
    FOREIGN KEY (TaxBusinessGroupId) REFERENCES TaxBusinessGroup(Id),
    FOREIGN KEY (OriginTaxJurisdictionId) REFERENCES TaxJurisdiction(Id),
    FOREIGN KEY (DestinationTaxJurisdictionId) REFERENCES TaxJurisdiction(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),

    FOREIGN KEY (SalesPersonId) REFERENCES Person(Id),
    FOREIGN KEY (ProjectId) REFERENCES Project(Id),
    FOREIGN KEY (CostCenterId) REFERENCES CostCenter(Id),
    FOREIGN KEY (BranchId) REFERENCES CompanyBranch(Id),

    FOREIGN KEY (PriceListTypeId) REFERENCES PriceListType(Id),
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id),

    FOREIGN KEY (PaymentMethodId) REFERENCES PaymentMethod(Id),
    FOREIGN KEY (PaymentTermId) REFERENCES PaymentTerm(Id),

    FOREIGN KEY (BillingCountryId) REFERENCES Country(Id),
    FOREIGN KEY (ShippingCountryId) REFERENCES Country(Id),

    FOREIGN KEY (SourceId) REFERENCES Trade(Id),
    FOREIGN KEY (CancelsTradeId) REFERENCES Trade(Id),
    FOREIGN KEY (CancelledByTradeId) REFERENCES Trade(Id),

    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (ModifiedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (PostedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (CancelledBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockTrade()
    {
        string TableName = "StockTrade";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    DocumentTypeId @NVARCHAR(40) @NOT_NULL,             -- Lookup -- controls numbering, posting behavior and movement direction
    Code @NVARCHAR(40) @NOT_NULL,                       -- Code Draft STK-YYYY-XXXXXX StockTrade
    TradeTypeId int default 0 @NOT_NULL,                -- [Hidden]
    
    WarehouseId @NVARCHAR(40) @NOT_NULL,                -- Lookup; Group Warehouses -- main/source warehouse
    ToWarehouseId @NVARCHAR(40) @NULL,                  -- Lookup; Group Warehouses -- destination warehouse, used only for transfers
 
    DocumentDate @DATE @NOT_NULL,                       -- Group Dates
    PostingDate @DATE @NULL,                            -- Group Dates -- date used for generated stock movements

    StatusId int default 1 @NOT_NULL,                   -- Enum TradeStatus

    TotalCostAmount @DECIMAL DEFAULT 0 @NOT_NULL,       -- total internal stock cost value posted by this document

    Remarks @NVARCHAR(512) @NULL,                       -- Memo; Group Notes -- internal notes

    IsLocked @BOOL DEFAULT 0 @NOT_NULL,                 -- Group Status
    IsCancelled @BOOL DEFAULT 0 @NOT_NULL,              -- Group Status

    CancelsStockTradeId @NVARCHAR(40) @NULL,            -- Locator StockTrade; Group Relations -- original document cancelled by this one
    CancelledByStockTradeId @NVARCHAR(40) @NULL,        -- Locator StockTrade; Group Relations -- reverse/cancellation document

    CreatedAt @DATE_TIME @NOT_NULL,                     -- Group Audit
    CreatedBy @NVARCHAR(40) @NOT_NULL,                  --  Lookup SYS_APP_USER; Group Audit
    ModifiedAt @DATE_TIME @NULL,                        -- Group Audit
    ModifiedBy @NVARCHAR(40) @NULL,                     --  Lookup SYS_APP_USER; Group Audit
    PostedAt @DATE_TIME @NULL,                          -- Group Audit
    PostedBy @NVARCHAR(40) @NULL,                       --  Lookup SYS_APP_USER; Group Audit
    CancelledAt @DATE_TIME @NULL,                       -- Group Audit
    CancelledBy @NVARCHAR(40) @NULL,                    --  Lookup SYS_APP_USER; Group Audit

    CONSTRAINT UQ_{TableName}_DocumentType_Code UNIQUE (DocumentTypeId, Code),

    FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (ToWarehouseId) REFERENCES Warehouse(Id),

    FOREIGN KEY (CancelsStockTradeId) REFERENCES StockTrade(Id),
    FOREIGN KEY (CancelledByStockTradeId) REFERENCES StockTrade(Id),

    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (ModifiedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (PostedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (CancelledBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockMovement()
    {
        string TableName = "StockMovement";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    TradeTypeId int default 0 @NOT_NULL,                -- Enum; [ReadOnlyUI]
    
    ProductId @NVARCHAR(40) @NOT_NULL,                  -- Locator Product
    WarehouseId @NVARCHAR(40) @NOT_NULL,                -- Lookup

    MovementDate @DATE @NOT_NULL,                       -- stock ledger date
    Direction int @NOT_NULL,                            -- 1=in, -1=out

    Quantity @DECIMAL DEFAULT 0 @NOT_NULL,              -- always positive, in movement unit
    PrimaryQuantity @DECIMAL DEFAULT 0 @NOT_NULL,       -- quantity in product primary unit

    UnitOfMeasureId @NVARCHAR(40) @NOT_NULL,            -- Lookup
    UnitOfMeasureName @NVARCHAR(40) @NOT_NULL,          -- Snapshot UnitOfMeasure.Name
    UnitRatio @DECIMAL DEFAULT 1 @NOT_NULL,             -- ratio to primary unit, ProductUnitOfMeasure.Ratio, converts line quantity to primary/base quantity

    UnitCost @DECIMAL DEFAULT 0 @NOT_NULL,              -- internal stock cost per primary unit at movement time
    CostAmount @DECIMAL DEFAULT 0 @NOT_NULL,            -- total stock cost posted by the movement

    SourceModule @NVARCHAR(64) @NOT_NULL,               -- source module name, e.g. Trade or StockTrade
    SourceTable @NVARCHAR(64) @NOT_NULL,                -- source line table, e.g. TradeLine or StockTradeLine
    SourceId @NVARCHAR(40) @NOT_NULL,                   -- source line Id

    DocumentTypeId @NVARCHAR(40) @NOT_NULL,             -- Lookup -- source document type
    DocumentCode @NVARCHAR(40) @NOT_NULL,               -- source document code snapshot
    DocumentDate @DATE @NOT_NULL,                       -- source document date snapshot    

    CreatedAt @DATE_TIME @NOT_NULL,
    CreatedBy @NVARCHAR(40) @NOT_NULL,                  --  Lookup SYS_APP_USER

    CONSTRAINT CHK_{TableName}_Direction CHECK (Direction IN (1, -1)),
    CONSTRAINT CHK_{TableName}_Quantity CHECK (Quantity >= 0),
    CONSTRAINT CHK_{TableName}_PrimaryQuantity CHECK (PrimaryQuantity >= 0),

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (UnitOfMeasureId) REFERENCES UnitOfMeasure(Id),
    FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),
    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockCount()
    {
        string TableName = "StockCount";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    Code @NVARCHAR(40) @NOT_NULL,                     -- Code Draft SC-YYYY-XXXXXX StockCount
    DocumentTypeId @NVARCHAR(40) @NOT_NULL,           -- Lookup -- controls numbering, posting behavior and movement direction
    TradeTypeId int default 0 @NOT_NULL,              -- [Hidden]
    
    WarehouseId @NVARCHAR(40) @NOT_NULL,              -- Lookup

    CountDate @DATE @NOT_NULL,

    StatusId int DEFAULT 1 @NOT_NULL,                 -- Enum TradeStatus; [ReadOnlyUI]

    Remarks @NBLOB_TEXT @NULL,                        -- LargeMemo; Group Notes

    CancelledDocumentId @NVARCHAR(40) @NULL,          -- Locator StockCount; Group Relations
    CancellationDocumentId @NVARCHAR(40) @NULL,       -- Locator StockCount; Group Relations

    CreatedAt @DATE_TIME @NOT_NULL,                   -- Group Audit
    CreatedBy @NVARCHAR(40) @NOT_NULL,                --  Lookup SYS_APP_USER; Group Audit
    ModifiedAt @DATE_TIME @NULL,                      -- Group Audit
    ModifiedBy @NVARCHAR(40) @NULL,                   --  Lookup SYS_APP_USER; Group Audit

    FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (CancelledDocumentId) REFERENCES StockCount(Id),
    FOREIGN KEY (CancellationDocumentId) REFERENCES StockCount(Id),
    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (ModifiedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_FinanceMovement()
    {
        string TableName = "FinanceMovement";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

   
    TradeTypeId int default 0 @NOT_NULL,              -- Enum; [ReadOnlyUI]
    MovementDate @DATE @NOT_NULL,

    CashAccountId @NVARCHAR(40) @NULL,                -- Lookup
    CompanyBankAccountId @NVARCHAR(40) @NULL,         -- Lookup

    Direction int @NOT_NULL,                          -- 1=in, -1=out

    Amount @DECIMAL DEFAULT 0 @NOT_NULL,

    CurrencyId @NVARCHAR(40) @NOT_NULL,              -- Lookup
    ExchangeRate @DECIMAL DEFAULT 1 @NOT_NULL,

    SourceModule @NVARCHAR(64) @NOT_NULL,
    SourceTable @NVARCHAR(64) @NOT_NULL,
    SourceId @NVARCHAR(40) @NOT_NULL,

    DocumentTypeId @NVARCHAR(40) @NOT_NULL,          -- Lookup
    DocumentCode @NVARCHAR(40) @NOT_NULL,
    DocumentDate @DATE @NOT_NULL,

    Remarks @NVARCHAR(512) @NULL,

    CreatedAt @DATE_TIME @NOT_NULL,
    CreatedBy @NVARCHAR(40) @NOT_NULL,               --  Lookup SYS_APP_USER

    CONSTRAINT CHK_{TableName}_Direction CHECK (Direction IN (1, -1)),
    CONSTRAINT CHK_{TableName}_Amount CHECK (Amount >= 0),

    FOREIGN KEY (CashAccountId) REFERENCES CashAccount(Id),
    FOREIGN KEY (CompanyBankAccountId) REFERENCES CompanyBankAccount(Id),
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id),
    FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),
    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_JournalEntry()
    {
        string TableName = "JournalEntry";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    Code @NVARCHAR(40) @NOT_NULL,                     -- Code Draft JE-YYYY-XXXXXX JournalEntry

    EntryDate @DATE @NOT_NULL,

    StatusId int DEFAULT 1 @NOT_NULL,                 -- Enum TradeStatus

    TotalDebit @DECIMAL DEFAULT 0 @NOT_NULL,
    TotalCredit @DECIMAL DEFAULT 0 @NOT_NULL,

    SourceModule @NVARCHAR(64) @NULL,                 -- Group Source
    SourceTable @NVARCHAR(64) @NULL,                  -- Group Source
    SourceId @NVARCHAR(40) @NULL,                     -- Group Source

    DocumentTypeId @NVARCHAR(40) @NULL,               -- Lookup; Group Document
    DocumentCode @NVARCHAR(40) @NULL,                 -- Group Document
    DocumentDate @DATE @NULL,                         -- Group Document
    TradeTypeId int default 0 @NOT_NULL,              -- Enum; [Hidden]

    Remarks @NBLOB_TEXT @NULL,                        -- LargeMemo; Group Notes

    CancelledDocumentId @NVARCHAR(40) @NULL,          -- Locator JournalEntry; Group Relations
    CancellationDocumentId @NVARCHAR(40) @NULL,       -- Locator JournalEntry; Group Relations

    CreatedAt @DATE_TIME @NOT_NULL,                   -- Group Audit
    CreatedBy @NVARCHAR(40) @NOT_NULL,                --  Lookup SYS_APP_USER; Group Audit
    ModifiedAt @DATE_TIME @NULL,                      -- Group Audit
    ModifiedBy @NVARCHAR(40) @NULL,                   --  Lookup SYS_APP_USER; Group Audit

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT CHK_{TableName}_Totals CHECK (TotalDebit = TotalCredit),

    FOREIGN KEY (DocumentTypeId) REFERENCES DocumentType(Id),
    FOREIGN KEY (CancelledDocumentId) REFERENCES JournalEntry(Id),
    FOREIGN KEY (CancellationDocumentId) REFERENCES JournalEntry(Id),
    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id),
    FOREIGN KEY (ModifiedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_TradeTax()
    {
        string TableName = "TradeTax";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,              -- -- Primary identifier

    TradeId @NVARCHAR(40) @NOT_NULL,                     -- Master -- Owning commercial document
    TaxRuleId @NVARCHAR(40) @NOT_NULL,                   -- Lookup -- Applied tax rule
    TaxRateId @NVARCHAR(40) @NOT_NULL,                   -- Lookup -- Applied tax rate
    TaxRatePercent @DECIMAL_(9,4) default 0 @NOT_NULL,   -- Snapshot TaxRate.Percent -- Percentage at calculation time

    TaxableAmount @DECIMAL default 0 @NOT_NULL,          -- -- Sum of taxable amounts for this rule
    TaxAmount @DECIMAL default 0 @NOT_NULL,              -- -- Sum of tax amounts for this rule
    TotalAmount @DECIMAL default 0 @NOT_NULL,            -- -- TaxableAmount plus TaxAmount

    CONSTRAINT UQ_{TableName}_Trade_TaxRule UNIQUE (TradeId, TaxRuleId),

    FOREIGN KEY (TradeId) REFERENCES Trade(Id),
    FOREIGN KEY (TaxRuleId) REFERENCES TaxRule(Id),
    FOREIGN KEY (TaxRateId) REFERENCES TaxRate(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_TradeLine()
    {
        string TableName = "TradeLine";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,              -- Primary identifier

    TradeId @NVARCHAR(40) @NOT_NULL,                     -- Master; [ReadOnlyUI] -- Owning commercial document

    DisplayOrder int @NOT_NULL,                          -- User-visible line order

    LineTypeId int default 1 @NOT_NULL,                  -- Enum TradeLineType -- Item or Service

    ProductId @NVARCHAR(40) @NULL,                       -- Locator Product
    ProductCode @NVARCHAR(40) @NULL,                     -- Snapshot Product.Code
    ProductName @NVARCHAR(128) @NULL,                    -- Snapshot Product.Name
    TaxProductGroupId @NVARCHAR(40) @NULL,               -- Lookup -- Tax classification copied from Product and stored as a line snapshot

    Description @NVARCHAR(256) @NULL,                    -- Commercial line description

    WarehouseId @NVARCHAR(40) @NULL,                     -- Lookup -- Optional line-level warehouse override

    UnitOfMeasureId @NVARCHAR(40) @NULL,                 -- Lookup -- Transaction unit of measure
    UnitOfMeasureName @NVARCHAR(40) @NULL,               -- Snapshot UnitOfMeasure.Name; [ReadOnlyUI]
    UnitRatio @DECIMAL default 1 @NOT_NULL,              -- [ReadOnlyUI] -- Ratio to the product primary unit

    Quantity @DECIMAL default 0 @NOT_NULL,               -- Quantity expressed in UnitOfMeasureId
    PrimaryUnitQuantity @DECIMAL default 0 @NOT_NULL,    -- [ReadOnlyUI] -- Quantity converted to the product primary unit

    ReservedQuantity @DECIMAL default 0 @NOT_NULL,       -- [ReadOnlyUI] -- Quantity reserved by warehouse processes
    ExecutedQuantity @DECIMAL default 0 @NOT_NULL,       -- [ReadOnlyUI] -- Quantity already executed or fulfilled

    TaxPercent @DECIMAL_(9,4) default 0 @NOT_NULL,       -- [ReadOnlyUI] -- Aggregate effective percentage of all tax components
    IsTaxExempt @BOOL default 0 @NOT_NULL,               -- [ReadOnlyUI] -- Indicates that the resolved tax treatment is exempt
    IsReverseCharge @BOOL default 0 @NOT_NULL,           -- [ReadOnlyUI] -- Indicates that tax liability shifts to the recipient

    UnitPrice @DECIMAL default 0 @NOT_NULL,              -- Price per selected unit before discounts and taxes

    GrossAmount @DECIMAL default 0 @NOT_NULL,            -- [ReadOnlyUI] -- Quantity multiplied by UnitPrice

    DiscountPercent @DECIMAL default 0 @NOT_NULL,        -- Line discount percentage
    DiscountAmount @DECIMAL default 0 @NOT_NULL,         -- Line discount monetary value

    NetUnitPrice @DECIMAL default 0 @NOT_NULL,           -- [ReadOnlyUI] -- Unit price after line discount

    NetAmount @DECIMAL default 0 @NOT_NULL,              -- [ReadOnlyUI] -- GrossAmount minus DiscountAmount
    DocumentDiscountAmount @DECIMAL default 0 @NOT_NULL, -- [ReadOnlyUI] -- Allocated share of the document discount
    TaxAmount @DECIMAL default 0 @NOT_NULL,              -- [ReadOnlyUI] -- Sum of all TradeLineTax components
    TotalAmount @DECIMAL default 0 @NOT_NULL,            -- [ReadOnlyUI] -- NetAmount minus DocumentDiscountAmount plus TaxAmount

    SourceTradeLineId @NVARCHAR(40) @NULL,               -- Locator TradeLine; [ReadOnlyUI] -- Source line for copied or corrective documents

    FOREIGN KEY (TradeId) REFERENCES Trade(Id),
    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (TaxProductGroupId) REFERENCES TaxProductGroup(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (UnitOfMeasureId) REFERENCES UnitOfMeasure(Id),
    FOREIGN KEY (SourceTradeLineId) REFERENCES TradeLine(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockBalance()
    {
        string TableName = "StockBalance";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    ProductId @NVARCHAR(40) @NOT_NULL,                  -- Locator Product
    WarehouseId @NVARCHAR(40) @NOT_NULL,                -- Lookup

    PrimaryQuantity @DECIMAL DEFAULT 0 @NOT_NULL,       -- current stock in product primary unit
    TotalCostAmount @DECIMAL DEFAULT 0 @NOT_NULL,       -- current total stock value
    AverageUnitCost @DECIMAL DEFAULT 0 @NOT_NULL,       -- TotalCostAmount / PrimaryQuantity

    LastMovementDate @DATE @NULL,
    LastMovementId @NVARCHAR(40) @NULL,

    CONSTRAINT UQ_{TableName}_Product_Warehouse UNIQUE (ProductId, WarehouseId),

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (LastMovementId) REFERENCES StockMovement(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockCountLine()
    {
        string TableName = "StockCountLine";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    StockCountId @NVARCHAR(40) @NOT_NULL,               -- Master

    DisplayOrder int @NOT_NULL,

    ProductId @NVARCHAR(40) @NOT_NULL,                  -- Locator Product
    ProductCode @NVARCHAR(40) @NOT_NULL,                -- Snapshot Product.Code 
    ProductName @NVARCHAR(96) @NOT_NULL,                -- Snapshot Product.Name

    UnitOfMeasureId @NVARCHAR(40) @NOT_NULL,          -- Lookup

    SystemQuantity @DECIMAL DEFAULT 0 @NOT_NULL,       -- [ReadOnlyUI]
    CountedQuantity @DECIMAL DEFAULT 0 @NOT_NULL,
    DifferenceQuantity @DECIMAL DEFAULT 0 @NOT_NULL,   -- [ReadOnlyUI]

    UnitCost @DECIMAL DEFAULT 0 @NOT_NULL,
    DifferenceCostAmount @DECIMAL DEFAULT 0 @NOT_NULL, -- [ReadOnlyUI]

    Remarks @NVARCHAR(512) @NULL,

    FOREIGN KEY (StockCountId) REFERENCES StockCount(Id),
    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (UnitOfMeasureId) REFERENCES UnitOfMeasure(Id) 
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_FinanceBalance()
    {
        string TableName = "FinanceBalance";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    CashAccountId @NVARCHAR(40) @NULL,                -- Lookup
    CompanyBankAccountId @NVARCHAR(40) @NULL,         -- Lookup

    Balance @DECIMAL DEFAULT 0 @NOT_NULL,

    LastMovementDate @DATE @NULL,
    LastMovementId @NVARCHAR(40) @NULL,

    FOREIGN KEY (CashAccountId) REFERENCES CashAccount(Id),
    FOREIGN KEY (CompanyBankAccountId) REFERENCES CompanyBankAccount(Id),
    FOREIGN KEY (LastMovementId) REFERENCES FinanceMovement(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_JournalEntryLine()
    {
        string TableName = "JournalEntryLine";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    JournalEntryId @NVARCHAR(40) @NOT_NULL,          -- Master

    DisplayOrder int @NOT_NULL,

    AccountId @NVARCHAR(40) @NOT_NULL,               -- Lookup

    DebitAmount @DECIMAL DEFAULT 0 @NOT_NULL,
    CreditAmount @DECIMAL DEFAULT 0 @NOT_NULL,

    CurrencyId @NVARCHAR(40) @NULL,                  -- Lookup
    ExchangeRate @DECIMAL DEFAULT 1 @NOT_NULL,

    ReferenceNo @NVARCHAR(40) @NULL,
    Remarks @NVARCHAR(512) @NULL,

    SourceModule @NVARCHAR(64) @NULL,
    SourceTable @NVARCHAR(64) @NULL,
    SourceId @NVARCHAR(40) @NULL, 

    CONSTRAINT CHK_{TableName}_DebitAmount CHECK (DebitAmount >= 0),
    CONSTRAINT CHK_{TableName}_CreditAmount CHECK (CreditAmount >= 0),

    FOREIGN KEY (JournalEntryId) REFERENCES JournalEntry(Id),
    FOREIGN KEY (AccountId) REFERENCES Account(Id),
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetDepreciationLine()
    {
        string TableName = "AssetDepreciationLine";
        string SqlText = $@"
CREATE TABLE {TableName} (
   Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    AssetId @NVARCHAR(40) @NOT_NULL,                  -- Master

    DepreciationDate @DATE @NOT_NULL,

    DepreciationAmount @DECIMAL DEFAULT 0 @NOT_NULL,
    AccumulatedDepreciation @DECIMAL DEFAULT 0 @NOT_NULL,
    BookValueAfter @DECIMAL DEFAULT 0 @NOT_NULL,

    JournalEntryId @NVARCHAR(40) @NULL,               -- Lookup

    Remarks @NVARCHAR(512) @NULL,

    CreatedAt @DATE_TIME @NOT_NULL,
    CreatedBy @NVARCHAR(40) @NOT_NULL,                --  Lookup SYS_APP_USER

    FOREIGN KEY (AssetId) REFERENCES Asset(Id),
    FOREIGN KEY (JournalEntryId) REFERENCES JournalEntry(Id),
    FOREIGN KEY (CreatedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_TradeLineTax()
    {
        string TableName = "TradeLineTax";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,              -- -- Primary identifier

    TradeLineId @NVARCHAR(40) @NOT_NULL,                 -- Master -- Owning commercial document line
    TaxRuleId @NVARCHAR(40) @NOT_NULL,                   -- Lookup -- Rule that produced this component
    TaxRateId @NVARCHAR(40) @NOT_NULL,                   -- Lookup -- Rate selected by the rule
    TaxJurisdictionId @NVARCHAR(40) @NOT_NULL,           -- Lookup -- Geographic authority that imposed this component
    TaxClauseId @NVARCHAR(40) @NULL,                     -- Lookup -- Legal explanation for exemption or special treatment

    SequenceNo int default 0 @NOT_NULL,                  -- -- Calculation order for compound tax components
    TaxCalculationTypeId int default 1 @NOT_NULL,        -- Enum TaxCalculationType -- Snapshot of the calculation method
    TaxRatePercent @DECIMAL_(9,4) default 0 @NOT_NULL,   -- Snapshot TaxRate.Percent -- Percentage at calculation time
    TaxableAmount @DECIMAL default 0 @NOT_NULL,          -- -- Amount on which this tax component was calculated
    TaxAmount @DECIMAL default 0 @NOT_NULL,              -- -- Calculated monetary value of this tax component

    IsExempt @BOOL default 0 @NOT_NULL,                  -- -- Snapshot indicating an exempt component
    IsReverseCharge @BOOL default 0 @NOT_NULL,           -- -- Snapshot indicating recipient tax liability
    TaxClauseText @NVARCHAR(512) @NULL,                  -- -- Snapshot of the printed legal explanation

    CONSTRAINT UQ_{TableName}_TradeLine_TaxRule UNIQUE (TradeLineId, TaxRuleId),

    FOREIGN KEY (TradeLineId) REFERENCES TradeLine(Id),
    FOREIGN KEY (TaxRuleId) REFERENCES TaxRule(Id),
    FOREIGN KEY (TaxRateId) REFERENCES TaxRate(Id),
    FOREIGN KEY (TaxJurisdictionId) REFERENCES TaxJurisdiction(Id),
    FOREIGN KEY (TaxClauseId) REFERENCES TaxClause(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockTradeLine()
    {
        string TableName = "StockTradeLine";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL PRIMARY KEY,

    StockTradeId @NVARCHAR(40) @NOT_NULL,               -- Master
    DisplayOrder int @NOT_NULL,

    ProductId @NVARCHAR(40) @NOT_NULL,                  -- Locator Product
    ProductCode @NVARCHAR(40) @NOT_NULL,                -- Snapshot Product.Code  
    ProductName @NVARCHAR(128) @NOT_NULL,               -- Snapshot Product.Name  

    WarehouseId @NVARCHAR(40) @NULL,                    -- Lookup -- optional source warehouse override

    UnitOfMeasureId @NVARCHAR(40) @NOT_NULL,            -- Lookup
    UnitOfMeasureName @NVARCHAR(40) @NOT_NULL,          -- Snapshot UnitOfMeasure.Name
    UnitRatio @DECIMAL DEFAULT 1 @NOT_NULL,             -- ratio to primary unit, ProductUnitOfMeasure.Ratio, converts line quantity to primary/base quantity

    Quantity @DECIMAL DEFAULT 0 @NOT_NULL,              -- always positive, direction is determined by DocumentType
    PrimaryQuantity @DECIMAL DEFAULT 0 @NOT_NULL,       -- Quantity * UnitRatio

    UnitCost @DECIMAL DEFAULT 0 @NOT_NULL,              -- internal stock cost per primary unit
    CostAmount @DECIMAL DEFAULT 0 @NOT_NULL,            -- PrimaryQuantity * UnitCost

    SourceTradeLineId @NVARCHAR(40) @NULL,              -- optional source commercial line
    SourceStockTradeLineId @NVARCHAR(40) @NULL,         -- optional source stock line, e.g. reversal/copy/adjustment flow

    Remarks @NVARCHAR(512) @NULL,                       -- internal line notes

    FOREIGN KEY (StockTradeId) REFERENCES StockTrade(Id),
    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (UnitOfMeasureId) REFERENCES UnitOfMeasure(Id),
    FOREIGN KEY (SourceTradeLineId) REFERENCES TradeLine(Id),
    FOREIGN KEY (SourceStockTradeLineId) REFERENCES StockTradeLine(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void AddCodeProviderPatternStatements()
    {
        string SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'Asset', 'Asset', 'AST-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-JournalEntry', 'DRAFT-JournalEntry', 'DRAFT-JE-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-PurchaseCancellation', 'DRAFT-PurchaseCancellation', 'DRAFT-PCAN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-PurchaseCreditNote', 'DRAFT-PurchaseCreditNote', 'DRAFT-PCN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-PurchaseDeliveryNote', 'DRAFT-PurchaseDeliveryNote', 'DRAFT-PDN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-PurchaseInvoice', 'DRAFT-PurchaseInvoice', 'DRAFT-PINV-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-PurchaseOrder', 'DRAFT-PurchaseOrder', 'DRAFT-PO-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-PurchaseReturn', 'DRAFT-PurchaseReturn', 'DRAFT-PRET-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-SalesCancellation', 'DRAFT-SalesCancellation', 'DRAFT-SCAN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-SalesCreditNote', 'DRAFT-SalesCreditNote', 'DRAFT-SCN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-SalesDeliveryNote', 'DRAFT-SalesDeliveryNote', 'DRAFT-SDN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-SalesInvoice', 'DRAFT-SalesInvoice', 'DRAFT-SINV-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-SalesOrder', 'DRAFT-SalesOrder', 'DRAFT-SO-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-SalesReturn', 'DRAFT-SalesReturn', 'DRAFT-SRET-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-StockCount', 'DRAFT-StockCount', 'DRAFT-SC-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'DRAFT-StockTrade', 'DRAFT-StockTrade', 'DRAFT-STK-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'JournalEntry', 'JournalEntry', 'JE-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PurchaseCancellation', 'PurchaseCancellation', 'PCAN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PurchaseCreditNote', 'PurchaseCreditNote', 'PCN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PurchaseDeliveryNote', 'PurchaseDeliveryNote', 'PDN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PurchaseInvoice', 'PurchaseInvoice', 'PINV-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PurchaseOrder', 'PurchaseOrder', 'PO-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PurchaseReturn', 'PurchaseReturn', 'PRET-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesCancellation', 'SalesCancellation', 'SCAN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesCreditNote', 'SalesCreditNote', 'SCN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesDeliveryNote', 'SalesDeliveryNote', 'SDN-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesInvoice', 'SalesInvoice', 'SINV-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesOrder', 'SalesOrder', 'SO-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesReturn', 'SalesReturn', 'SRET-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'StockCount', 'StockCount', 'SC-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'StockTrade', 'StockTrade', 'STK-YYYY-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
    }

    // ● protected
    protected override void RegisterInternal()
    {
        RegisterTable_DocumentType();
        RegisterTable_StockReservation();
        RegisterTable_Account();
        RegisterTable_Asset();
        RegisterTable_Trade();
        RegisterTable_StockTrade();
        RegisterTable_StockMovement();
        RegisterTable_StockCount();
        RegisterTable_FinanceMovement();
        RegisterTable_JournalEntry();
        RegisterTable_TradeTax();
        RegisterTable_TradeLine();
        RegisterTable_StockBalance();
        RegisterTable_StockCountLine();
        RegisterTable_FinanceBalance();
        RegisterTable_JournalEntryLine();
        RegisterTable_AssetDepreciationLine();
        RegisterTable_TradeLineTax();
        RegisterTable_StockTradeLine();
        AddCodeProviderPatternStatements();
    }

    // ● construction
    public SchemaVersion2()
    {
    }

    // ● properties
    public override int VersionNumber { get; } = 2;
}