/*
 * <auto-generated>
 * This file was generated by Tripous RegBuilder.
 * Do not edit this file manually.
 * </auto-generated>
 *
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Data;

public partial class SchemaVersion1: SchemaVersionDef
{
    // ● private
    void RegisterTable_SYS_LOG()
    {
        string TableName = "SYS_LOG";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key
    ,Year int @NOT_NULL
    ,Month int @NOT_NULL
    ,DayOfMonth int @NOT_NULL
    ,LogTime @NVARCHAR(20) @NOT_NULL
    ,User @NVARCHAR(96) @NOT_NULL
    ,Host @NVARCHAR(96) @NOT_NULL
    ,Level @NVARCHAR(96) @NOT_NULL
    ,Source @NVARCHAR(512) @NOT_NULL
    ,Scope @NVARCHAR(512) @NOT_NULL
    ,EventId @NVARCHAR(96) @NOT_NULL
    ,Message @NBLOB_TEXT @NOT_NULL          -- LargeMemo 
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_SYS_NUMBER_SERIES()
    {
        string TableName = "SYS_NUMBER_SERIES";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id              @NVARCHAR(40) @NOT_NULL primary key,
    Code            @NVARCHAR(40) @NOT_NULL,
    Name            @NVARCHAR(96) @NOT_NULL,
    Pattern         @NVARCHAR(64) @NOT_NULL,
    ResetPeriodId   integer default 0 @NOT_NULL, -- Enum
    NextNumber      integer default 1 @NOT_NULL,
    LastResetValue  @NVARCHAR(16) @NULL,
    IsActive        @BOOL default 1 @NOT_NULL,

    CONSTRAINT UQ_NumberSeries_Code UNIQUE (Code),
    CONSTRAINT UQ_NumberSeries_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_SYS_STR_RES()
    {
        string TableName = "SYS_STR_RES";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Lang @NVARCHAR(12) @NOT_NULL,           -- e.g. en, el
    ResKey @NVARCHAR(96) @NOT_NULL,
    ResValue @NBLOB_TEXT @NOT_NULL,         -- Memo

    CONSTRAINT UQ_{TableName}_Lang_ResKey UNIQUE (Lang, ResKey)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_SYS_APP_USER()
    {
        string TableName = "SYS_APP_USER";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    UserName @NVARCHAR(64) @NOT_NULL,
    Password @NVARCHAR(512) @NOT_NULL,
    Salt @NVARCHAR(256) @NOT_NULL,

    FullName @NVARCHAR(96) @NOT_NULL,

    UserLevelId int @NOT_NULL,                     -- Enum UserLevel
    CultureCode @NVARCHAR(16) @NULL,

    Email @NVARCHAR(96) @NULL,
    Phone @NVARCHAR(40) @NULL,

    LastLoginAt @DATE_TIME @NULL,
    PasswordChangedAt @DATE_TIME @NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_UserName UNIQUE (UserName)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_CustomerCategory()
    {
        string TableName = "CustomerCategory";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_SupplierCategory()
    {
        string TableName = "SupplierCategory";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductBrand()
    {
        string TableName = "ProductBrand";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_DiscountCategory()
    {
        string TableName = "DiscountCategory";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_UnitOfMeasure()
    {
        string TableName = "UnitOfMeasure";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_TaxOffice()
    {
        string TableName = "TaxOffice";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Bank()
    {
        string TableName = "Bank";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ExpenseCategory()
    {
        string TableName = "ExpenseCategory";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PaymentMethod()
    {
        string TableName = "PaymentMethod";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_SalesPerson()
    {
        string TableName = "SalesPerson";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,                -- Code XXXX
    Name @NVARCHAR(96) @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Carrier()
    {
        string TableName = "Carrier";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Country()
    {
        string TableName = "Country";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Iso2 @NVARCHAR(2) @NOT_NULL,
    Iso3 @NVARCHAR(3) @NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Currency()
    {
        string TableName = "Currency";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    Symbol @NVARCHAR(8) @NOT_NULL,
    Decimals int default 2 @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_VatRate()
    {
        string TableName = "VatRate";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    Percent @DECIMAL_(5,2) @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PaymentTerm()
    {
        string TableName = "PaymentTerm";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,    -- business code
    Name @NVARCHAR(96) @NOT_NULL,    -- display title

    Days integer @NOT_NULL,          -- payment due days

    IsActive @BOOL default 1 @NOT_NULL,

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductGroup()
    {
        string TableName = "ProductGroup";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL, -- business code
    Name @NVARCHAR(96) @NOT_NULL, -- display title

    IsSystem @BOOL default 0 @NOT_NULL, -- protected/system group
    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,     -- ui display color
    IconName @NVARCHAR(96) @NULL,  -- ui icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_FiscalYear()
    {
        string TableName = "FiscalYear";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,    -- business code
    Name @NVARCHAR(96) @NOT_NULL,    -- display title

    StartDate @DATE @NOT_NULL,       -- fiscal year start
    EndDate @DATE @NOT_NULL,         -- fiscal year end

    IsActive @BOOL default 1 @NOT_NULL,
    IsClosed @BOOL default 0 @NOT_NULL, -- no more postings allowed

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Language()
    {
        string TableName = "Language";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(16) @NOT_NULL,                   -- ISO code, e.g. EN, EL, DE
    Name @NVARCHAR(96) @NOT_NULL,                   -- display title

    CultureName @NVARCHAR(32) @NULL,                -- en-US, el-GR, de-DE

    IsDefault @BOOL default 0 @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,

    IsRightToLeft @BOOL default 0 @NOT_NULL,        -- Arabic, Hebrew, etc.

    Color @NVARCHAR(32) @NULL,                      -- ui display color
    IconName @NVARCHAR(96) @NULL,                   -- ui icon / flag icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PersonRoleType()
    {
        string TableName = "PersonRoleType";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,

    Color @NVARCHAR(32) @NULL,
    IconName @NVARCHAR(96) @NULL,

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_StockReason()
    {
        string TableName = "StockReason";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,                   -- business code
    Name @NVARCHAR(96) @NOT_NULL,                   -- display title

    StockDirection integer default 0 @NOT_NULL,     -- 1=in, -1=out, 0=no stock effect

    AffectsCost @BOOL default 0 @NOT_NULL,          -- affects inventory valuation
    RequiresRemarks @BOOL default 0 @NOT_NULL,      -- user must enter explanation

    IsSystem @BOOL default 0 @NOT_NULL,             -- protected/system-defined reason
    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,                      -- ui display color
    IconName @NVARCHAR(96) @NULL,                   -- ui icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ContactType()
    {
        string TableName = "ContactType";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    Name                @NVARCHAR(96) @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetCategory()
    {
        string TableName = "AssetCategory";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    Name                @NVARCHAR(96) @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetLocation()
    {
        string TableName = "AssetLocation";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    Name                @NVARCHAR(96) @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL 
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetDepreciationMethod()
    {
        string TableName = "AssetDepreciationMethod";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    Name                @NVARCHAR(96) @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL 
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductDimension()
    {
        string TableName = "ProductDimension";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Name @NVARCHAR(96) @NOT_NULL,

    IsActive @BOOL default 1 @NOT_NULL
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductAttributeGroup()
    {
        string TableName = "ProductAttributeGroup";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Name @NVARCHAR(96) @NOT_NULL,

    DisplayOrder int default 0 @NOT_NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_SYS_CONFIG()
    {
        string TableName = "SYS_CONFIG";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ScopeId int @NOT_NULL,                 -- Enum ConfigScope -- System, Company, User
    OwnerKey @NVARCHAR(96) @NULL,          -- CompanyId, UserName, or empty string for System 

    Name @NVARCHAR(128) @NOT_NULL,         -- ConfigPropertyDef.Name

    Value @NVARCHAR(512) @NULL,            -- scalar values
    TextValue @NBLOB_TEXT @NULL,           -- Memo/Object values

    ModifiedAt @DATE_TIME @NULL,           -- [ReadOnlyUI]
    ModifiedBy @NVARCHAR(40) @NULL,        -- Lookup SYS_APP_USER; [ReadOnlyUI]

    CONSTRAINT UQ_{TableName}_Scope_Owner_Name UNIQUE (ScopeId, OwnerKey, Name),
    FOREIGN KEY (ModifiedBy) REFERENCES  SYS_APP_USER(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PriceListType()
    {
        string TableName = "PriceListType";
        string SqlText = $@"
CREATE TABLE {TableName} (
     Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,

    CurrencyId @NVARCHAR(40) @NOT_NULL,             -- Lookup

    IsTaxIncluded @BOOL default 1 @NOT_NULL,
    IsDefault @BOOL default 0 @NOT_NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,
    IconName @NVARCHAR(96) @NULL,

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),

    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Company()
    {
        string TableName = "Company";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,           -- Code XXXXXX
    Name @NVARCHAR(96) @NOT_NULL,
    Title @NVARCHAR(160) @NULL,
    TaxNumber @NVARCHAR(32) @NOT_NULL,
    TaxOfficeId @NVARCHAR(40) @NULL,        -- Lookup
    CountryId @NVARCHAR(40) @NULL,      -- Lookup
    CurrencyId @NVARCHAR(40) @NULL,     -- Lookup
    AddressLine1 @NVARCHAR(160) @NULL,
    AddressLine2 @NVARCHAR(160) @NULL,
    City @NVARCHAR(96) @NULL,
    PostalCode @NVARCHAR(16) @NULL,
    Phone @NVARCHAR(32) @NULL,
    Email @NVARCHAR(96) @NULL,
    Website @NVARCHAR(96) @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (TaxOfficeId) REFERENCES TaxOffice(Id),
    FOREIGN KEY (CountryId) REFERENCES Country(Id),
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_TaxCategory()
    {
        string TableName = "TaxCategory";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,               -- business code
    Name @NVARCHAR(96) @NOT_NULL,               -- display title

    VatRateId @NVARCHAR(40) @NULL,              -- Lookup   -- default vat rate

    IsDomestic @BOOL default 0 @NOT_NULL,
    IsEuropeanUnion @BOOL default 0 @NOT_NULL,
    IsThirdCountry @BOOL default 0 @NOT_NULL,

    IsTaxExempt @BOOL default 0 @NOT_NULL,
    IsReverseCharge @BOOL default 0 @NOT_NULL,
    IsIntrastat @BOOL default 0 @NOT_NULL,
    IsVies @BOOL default 0 @NOT_NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,       -- ui display color
    IconName @NVARCHAR(96) @NULL,    -- ui icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (VatRateId) REFERENCES VatRate(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_FiscalPeriod()
    {
        string TableName = "FiscalPeriod";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    YearId  @NVARCHAR(40) @NOT_NULL,            -- Master

    Code @NVARCHAR(40) @NOT_NULL,               -- business code
    Name @NVARCHAR(96) @NOT_NULL,               -- display title

    PeriodNo integer @NOT_NULL,                 -- 1..12 or custom sequence

    StartDate @DATE @NOT_NULL,
    EndDate @DATE @NOT_NULL,

    IsClosed @BOOL default 0 @NOT_NULL,         -- no postings allowed

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_FiscalYear_PeriodNo UNIQUE (YearId, PeriodNo),

    FOREIGN KEY (YearId) REFERENCES FiscalYear(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Person()
    {
        string TableName = "Person";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,
    Code @NVARCHAR(40) @NOT_NULL,

    Name @NVARCHAR(96) @NOT_NULL,
    Title @NVARCHAR(160) @NULL,

    TaxNumber @NVARCHAR(32) @NULL,                  -- Group Tax
    TaxOfficeId @NVARCHAR(40) @NULL,                -- Lookup; Group Tax

    CountryId @NVARCHAR(40) @NULL,                  -- Lookup; Group Preferences
    CurrencyId @NVARCHAR(40) @NULL,                 -- Lookup; Group Preferences
    LanguageId @NVARCHAR(40) @NULL,                 -- Lookup; Group Preferences -- preferred language

    AddressLine1 @NVARCHAR(160) @NULL,              -- Group Address
    AddressLine2 @NVARCHAR(160) @NULL,              -- Group Address
    City @NVARCHAR(96) @NULL,                       -- Group Address
    PostalCode @NVARCHAR(16) @NULL,                 -- Group Address

    Phone @NVARCHAR(32) @NULL,                      -- Group Address
    Mobile @NVARCHAR(32) @NULL,                     -- Group Address
    Email @NVARCHAR(96) @NULL,                      -- Group Address
    Website @NVARCHAR(96) @NULL,                    -- Group Address

    ContactPerson @NVARCHAR(96) @NULL,              -- Group Address

    Notes @NBLOB_TEXT @NULL,                        -- LargeMemo; Group Notes

    IsCompany @BOOL default 1 @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,                      -- Group Appearance
    IconName @NVARCHAR(96) @NULL,                   -- Group Appearance

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (TaxOfficeId) REFERENCES TaxOffice(Id),
    FOREIGN KEY (CountryId) REFERENCES Country(Id),
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id),
    FOREIGN KEY (LanguageId) REFERENCES Language(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Category()
    {
        string TableName = "Category";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ParentId @NVARCHAR(40) @NULL,                   -- Lookup       -- parent category

    Code @NVARCHAR(40) @NOT_NULL,                   -- business code
    Name @NVARCHAR(96) @NOT_NULL,                   -- display title

    LevelNo integer default 0 @NOT_NULL,            -- optional hierarchy level

    SortNo integer default 0 @NOT_NULL,             -- display order

    VatRateId @NVARCHAR(40) @NULL,                  -- Lookup       -- default vat rate
    RevenueAccount @NVARCHAR(40) @NULL,             -- optional accounting account
    ExpenseAccount @NVARCHAR(40) @NULL,             -- optional accounting account

    IsSystem @BOOL default 0 @NOT_NULL,             -- protected/system category
    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,                      -- ui display color
    IconName @NVARCHAR(96) @NULL,                   -- ui icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (ParentId) REFERENCES Category(Id),
    FOREIGN KEY (VatRateId) REFERENCES VatRate(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_FixedAsset()
    {
        string TableName = "FixedAsset";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,

    Code                @NVARCHAR(40) @NOT_NULL, -- Code AST-XXXXXX
    Name                @NVARCHAR(96) @NOT_NULL,

    AssetCategoryId     @NVARCHAR(40) @NOT_NULL, -- Lookup
    AssetLocationId     @NVARCHAR(40) @NOT_NULL, -- Lookup
    AssetDepreciationMethodId   @NVARCHAR(40) @NULL,         -- Lookup

    PurchaseDate           @DATE @NULL,
    PurchaseValue          @DECIMAL_(18, 4) @NULL,

    UsefulLifeMonths       int @NULL,
    DepreciationRate       @DECIMAL_(18, 4) @NULL,    

    SerialNumber        @NVARCHAR(96) @NULL,
    Manufacturer        @NVARCHAR(96) @NULL,
    Model               @NVARCHAR(96) @NULL,

    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo
 

    FOREIGN KEY (AssetCategoryId) REFERENCES AssetCategory(Id),
    FOREIGN KEY (AssetLocationId) REFERENCES AssetLocation(Id),
    FOREIGN KEY (AssetDepreciationMethodId) REFERENCES AssetDepreciationMethod(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductDimensionValue()
    {
        string TableName = "ProductDimensionValue";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ProductDimensionId @NVARCHAR(40) @NOT_NULL,   -- Master

    Name @NVARCHAR(96) @NOT_NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    FOREIGN KEY (ProductDimensionId) REFERENCES ProductDimension(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_CompanyBranch()
    {
        string TableName = "CompanyBranch";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    CompanyId @NVARCHAR(40) @NOT_NULL,          -- Master
    Code @NVARCHAR(40) @NOT_NULL,                
    Name @NVARCHAR(96) @NOT_NULL,
    AddressLine1 @NVARCHAR(160) @NULL,
    AddressLine2 @NVARCHAR(160) @NULL,
    City @NVARCHAR(96) @NULL,
    PostalCode @NVARCHAR(16) @NULL,
    CountryId @NVARCHAR(40) @NOT_NULL,          -- Lookup
    Phone @NVARCHAR(32) @NULL,
    Email @NVARCHAR(96) @NULL,
    IsPrimary int default 0 @NOT_NULL,
    IsActive int default 1 @NOT_NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (CompanyId) REFERENCES Company(Id),
    FOREIGN KEY (CountryId) REFERENCES Country(Id),
    CONSTRAINT UQ_{TableName}_CompanyId_Code UNIQUE (CompanyId, Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_CompanyBankAccount()
    {
        string TableName = "CompanyBankAccount";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id  @NVARCHAR(40)  @NOT_NULL primary key,
    CompanyId @NVARCHAR(40) @NOT_NULL,              -- Master
    Code @NVARCHAR(40) @NOT_NULL,
    Name @NVARCHAR(96) @NOT_NULL,
    BankName @NVARCHAR(96) @NOT_NULL,
    Iban @NVARCHAR(40) @NOT_NULL,
    SwiftBic @NVARCHAR(16) @NULL,
    CurrencyId @NVARCHAR(40) @NOT_NULL,             -- Lookup
    IsDefault int default 0 @NOT_NULL,
    IsActive int default 1 @NOT_NULL,
    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),
    FOREIGN KEY (CompanyId) REFERENCES Company(Id),
    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id),
    CONSTRAINT UQ_{TableName}_CompanyId_Code UNIQUE (CompanyId, Code)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PersonRole()
    {
        string TableName = "PersonRole";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    PersonId @NVARCHAR(40) @NOT_NULL,           -- Master
    RoleTypeId @NVARCHAR(40) @NOT_NULL,         -- Lookup 

    Remarks @NBLOB_TEXT @NULL,

    FOREIGN KEY (PersonId) REFERENCES Person(Id),
    FOREIGN KEY (RoleTypeId) REFERENCES PersonRoleType(Id),

    CONSTRAINT UQ_{TableName}_Person_Role UNIQUE (PersonId, RoleTypeId)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_CostCenter()
    {
        string TableName = "CostCenter";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,                   -- business code
    Name @NVARCHAR(96) @NOT_NULL,                   -- display title

    ParentCostCenterId @NVARCHAR(40) @NULL,         -- Lookup   -- optional hierarchy parent
    ManagerPersonId @NVARCHAR(40) @NULL,            -- Locator Manager  -- responsible person

    StartDate @DATE @NULL,                          -- activation date
    EndDate @DATE @NULL,                            -- deactivation date

    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,                      -- ui display color
    IconName @NVARCHAR(96) @NULL,                   -- ui icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (ParentCostCenterId) REFERENCES CostCenter(Id),
    FOREIGN KEY (ManagerPersonId) REFERENCES Person(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Product()
    {
        string TableName = "Product";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,                           -- Code XXXXXX -- business code
    Name @NVARCHAR(96) @NOT_NULL,                           -- display title

    ProductTypeId integer @NOT_NULL,                        -- Enum         -- Goods, Service, RawMaterial

    CategoryId @NVARCHAR(40) @NULL,                         -- Lookup
    VatRateId @NVARCHAR(40) @NULL,                          -- Lookup

    PrimaryUnitOfMeasureId @NVARCHAR(40) @NOT_NULL,         -- Lookup       -- inventory/base unit

    Barcode @NVARCHAR(64) @NULL,

    Weight @DECIMAL @NULL,
    Volume @DECIMAL @NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,
    IconName @NVARCHAR(96) @NULL,

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (CategoryId) REFERENCES Category(Id),
    FOREIGN KEY (VatRateId) REFERENCES VatRate(Id),
    FOREIGN KEY (PrimaryUnitOfMeasureId) REFERENCES UnitOfMeasure(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PersonAddress()
    {
        string TableName = "PersonAddress";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    PersonId            @NVARCHAR(40) @NOT_NULL,                -- Master
    AddressTypeId       int @NOT_NULL,                          -- Enum AddressType
    Code                @NVARCHAR(40) @NULL,                    -- Code ADR-XXXXXX

    Name                @NVARCHAR(96) @NULL,
    CountryId           @NVARCHAR(40) @NULL,                    -- Lookup
    Region              @NVARCHAR(96) @NULL,
    City                @NVARCHAR(96) @NULL,
    PostalCode          @NVARCHAR(40) @NULL,

    AddressLine1        @NVARCHAR(96) @NULL,
    AddressLine2        @NVARCHAR(96) @NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,                      -- LargeMemo 

    FOREIGN KEY (PersonId) REFERENCES Person(Id),
    FOREIGN KEY (CountryId) REFERENCES Country(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PersonContact()
    {
        string TableName = "PersonContact";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    PersonId            @NVARCHAR(40) @NOT_NULL,                -- Master
    ContactTypeId       @NVARCHAR(40) @NOT_NULL,                -- Lookup

    Name                @NVARCHAR(96) @NOT_NULL,
    JobTitle            @NVARCHAR(96) @NULL,

    Phone               @NVARCHAR(40) @NULL,
    Mobile              @NVARCHAR(40) @NULL,
    Email               @NVARCHAR(96) @NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,                      -- LargeMemo
 

    FOREIGN KEY (PersonId) REFERENCES Person(Id),
    FOREIGN KEY (ContactTypeId) REFERENCES ContactType(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PersonBankAccount()
    {
        string TableName = "PersonBankAccount";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    PersonId            @NVARCHAR(40) @NOT_NULL,                -- Master

    BankId              @NVARCHAR(40) @NOT_NULL,                -- Lookup
    Name                @NVARCHAR(96) @NOT_NULL,

    Iban                @NVARCHAR(40) @NULL,
    SwiftCode           @NVARCHAR(40) @NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,                      -- LargeMemo 

    FOREIGN KEY (PersonId) REFERENCES Person(Id),
    FOREIGN KEY (BankId) REFERENCES Bank(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetAssignment()
    {
        string TableName = "AssetAssignment";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    FixedAssetId        @NVARCHAR(40) @NOT_NULL,                -- Master

    PersonId            @NVARCHAR(40) @NULL,                    -- Locator Employee

    AssignmentDate      @DATE @NULL,
    ReturnDate          @DATE @NULL,

    Notes               @NBLOB_TEXT @NULL,                      -- LargeMemo
 

    FOREIGN KEY (FixedAssetId) REFERENCES FixedAsset(Id),
    FOREIGN KEY (PersonId) REFERENCES Person(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetMaintenance()
    {
        string TableName = "AssetMaintenance";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    FixedAssetId        @NVARCHAR(40) @NOT_NULL, -- Master

    Date                @DATE @NOT_NULL,
    Description         @NVARCHAR(255) @NOT_NULL,

    Cost                @DECIMAL_(18, 4) @NULL,

    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo 

    FOREIGN KEY (FixedAssetId) REFERENCES FixedAsset(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetDocument()
    {
        string TableName = "AssetDocument";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    FixedAssetId        @NVARCHAR(40) @NOT_NULL, -- Master

    Name                @NVARCHAR(96) @NOT_NULL,
    FileName            @NVARCHAR(255) @NULL,
    Description         @NVARCHAR(255) @NULL,

    BlobText            @NBLOB_TEXT @NULL,       -- LargeMemo 

    FOREIGN KEY (FixedAssetId) REFERENCES FixedAsset(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_AssetInsurance()
    {
        string TableName = "AssetInsurance";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    FixedAssetId @NVARCHAR(40) @NOT_NULL,         -- Master

    PolicyNumber @NVARCHAR(96) @NULL,

    StartDate @DATE @NULL,
    EndDate @DATE @NULL,

    Amount @DECIMAL_(18, 4) @NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Notes @NBLOB_TEXT @NULL,

    FOREIGN KEY (FixedAssetId) REFERENCES FixedAsset(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_PriceList()
    {
        string TableName = "PriceList";
        string SqlText = $@"
CREATE TABLE {TableName} (
   Id @NVARCHAR(40) @NOT_NULL primary key,

    PriceListTypeId @NVARCHAR(40) @NOT_NULL,        -- Lookup

    DiscountCategoryId @NVARCHAR(40) @NULL,         -- Lookup
    CustomerId @NVARCHAR(40) @NULL,                 -- Locator Customer

    ProductId @NVARCHAR(40) @NOT_NULL,              -- Locator Product
    UnitOfMeasureId @NVARCHAR(40) @NOT_NULL,        -- Lookup

    MinQuantity @DECIMAL_(18, 4) default 0 @NOT_NULL,

    UnitPrice @DECIMAL_(18, 4) @NOT_NULL,

    ValidFrom @DATE @NULL,
    ValidTo @DATE @NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Remarks @NBLOB_TEXT @NULL,

    FOREIGN KEY (PriceListTypeId) REFERENCES PriceListType(Id),
    FOREIGN KEY (DiscountCategoryId) REFERENCES DiscountCategory(Id),
    FOREIGN KEY (CustomerId) REFERENCES Person(Id),
    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (UnitOfMeasureId) REFERENCES UnitOfMeasure(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductGroups()
    {
        string TableName = "ProductGroups";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ProductId @NVARCHAR(40) @NOT_NULL,  -- Master
    GroupId @NVARCHAR(40) @NOT_NULL,    -- Lookup

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Product_Group UNIQUE (ProductId, GroupId),

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (GroupId) REFERENCES ProductGroup(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Warehouse()
    {
        string TableName = "Warehouse";
        string SqlText = $@"
CREATE TABLE {TableName} (
                             Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,                       -- Code WH-XXXXXX -- business code
    Name @NVARCHAR(96) @NOT_NULL,                       -- display title

    CompanyId @NVARCHAR(40) @NOT_NULL,                  -- Lookup -- owner company
    BranchId @NVARCHAR(40) @NULL,                       -- Lookup -- optional company branch

    WarehouseTypeId integer default 0 @NOT_NULL,        -- Enum -- Main, Store, Transit, Production, Scrap, Virtual

    AddressLine1 @NVARCHAR(160) @NULL,                  -- Group Address
    AddressLine2 @NVARCHAR(160) @NULL,                  -- Group Address
    City @NVARCHAR(96) @NULL,                           -- Group Address
    PostalCode @NVARCHAR(16) @NULL,                     -- Group Address
    CountryId @NVARCHAR(40) @NULL,                      -- Lookup; Group Address

    Phone @NVARCHAR(32) @NULL,                          -- Group Address
    Email @NVARCHAR(96) @NULL,                          -- Group Address

    ResponsiblePersonId @NVARCHAR(40) @NULL,            -- Locator Employee; Group Settings -- person responsible for warehouse

    IsActive @BOOL default 1 @NOT_NULL,                 -- Group Settings
    IsVirtual @BOOL default 0 @NOT_NULL,                -- Group Settings -- logical/non-physical warehouse
    AllowNegativeStock @BOOL default 0 @NOT_NULL,       -- Group Settings -- allow stock below zero
    AffectsAvailability @BOOL default 1 @NOT_NULL,      -- Group Settings -- participates in available stock

    Color @NVARCHAR(32) @NULL,                          -- Group Appearance -- ui display color
    IconName @NVARCHAR(96) @NULL,                       -- Group Appearance -- ui icon

    Remarks @NBLOB_TEXT @NULL,                          -- LargeMemo; Group Notes

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (CompanyId) REFERENCES Company(Id),
    FOREIGN KEY (BranchId) REFERENCES CompanyBranch(Id),
    FOREIGN KEY (CountryId) REFERENCES Country(Id),
    FOREIGN KEY (ResponsiblePersonId) REFERENCES Person(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_Project()
    {
        string TableName = "Project";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    Code @NVARCHAR(40) @NOT_NULL,                   -- Code YYYY-XXXX -- business code
    Name @NVARCHAR(96) @NOT_NULL,                   -- display title

    CustomerId @NVARCHAR(40) @NULL,                 -- Locator Customer    -- customer/person owner

    ProjectStatusId integer default 0 @NOT_NULL,    -- Enum         -- Draft, Active, Completed, Cancelled

    StartDate @DATE @NULL,
    EndDate @DATE @NULL,

    CostCenterId @NVARCHAR(40) @NULL,

    ManagerPersonId @NVARCHAR(40) @NULL,            -- Locator Manager     -- responsible person

    IsActive @BOOL default 1 @NOT_NULL,

    Color @NVARCHAR(32) @NULL,                      -- ui display color
    IconName @NVARCHAR(96) @NULL,                   -- ui icon

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Code UNIQUE (Code),
    CONSTRAINT UQ_{TableName}_Name UNIQUE (Name),

    FOREIGN KEY (CustomerId) REFERENCES Person(Id),
    FOREIGN KEY (CostCenterId) REFERENCES CostCenter(Id),
    FOREIGN KEY (ManagerPersonId) REFERENCES Person(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductCategory()
    {
        string TableName = "ProductCategory";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ProductId @NVARCHAR(40) @NOT_NULL,                      -- Master
    CategoryId @NVARCHAR(40) @NOT_NULL,                     -- Lookup

    IsActive @BOOL default 1 @NOT_NULL, 

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (CategoryId) REFERENCES Category(Id),

    CONSTRAINT UQ_{TableName}_Product_Category UNIQUE (ProductId, CategoryId)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductUnitOfMeasure()
    {
        string TableName = "ProductUnitOfMeasure";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ProductId @NVARCHAR(40) @NOT_NULL,                  -- Master
    UnitId @NVARCHAR(40) @NOT_NULL,                     -- Lookup

    Ratio @DECIMAL @NOT_NULL,                           -- ratio to primary unit

    Barcode @NVARCHAR(64) @NULL,

    IsSalesDefault @BOOL default 0 @NOT_NULL,
    IsPurchaseDefault @BOOL default 0 @NOT_NULL,

    IsActive @BOOL default 1 @NOT_NULL,

    Remarks @NBLOB_TEXT @NULL,

    CONSTRAINT UQ_{TableName}_Product_Unit UNIQUE (ProductId, UnitId),

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (UnitId) REFERENCES UnitOfMeasure(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductBarcode()
    {
        string TableName = "ProductBarcode";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    ProductId           @NVARCHAR(40) @NOT_NULL, -- Master

    Barcode             @NVARCHAR(512) @NOT_NULL,
    Name                @NVARCHAR(96) @NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo 

    FOREIGN KEY (ProductId) REFERENCES Product(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductSupplier()
    {
        string TableName = "ProductSupplier";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    ProductId           @NVARCHAR(40) @NOT_NULL, -- Master

    SupplierId          @NVARCHAR(40) @NOT_NULL, -- Locator Supplier
    SupplierCode        @NVARCHAR(96) @NULL,     -- TitleKey Supplier Product Code

    LeadDays            int @NULL,
    LastCost            @DECIMAL_(18, 4) @NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo
 

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (SupplierId) REFERENCES Person(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_BillOfMaterial()
    {
        string TableName = "BillOfMaterial";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    ProductId           @NVARCHAR(40) @NOT_NULL, -- Master

    Code                @NVARCHAR(40) @NOT_NULL, -- Code BOM-XXXXXX
    Name                @NVARCHAR(96) @NOT_NULL,

    Quantity            @DECIMAL_(18, 4) @NOT_NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo
 

    FOREIGN KEY (ProductId) REFERENCES Product(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_CashAccount()
    {
        string TableName = "CashAccount";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,

    Code                @NVARCHAR(40) @NOT_NULL, -- Code CASH-XXXXXX
    Name                @NVARCHAR(96) @NOT_NULL,

    CurrencyId          @NVARCHAR(40) @NOT_NULL, -- Lookup
    CompanyBranchId     @NVARCHAR(40) @NULL,     -- Lookup

    Balance             @DECIMAL_(18, 4) @NULL,

    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo
 

    FOREIGN KEY (CurrencyId) REFERENCES Currency(Id),
    FOREIGN KEY (CompanyBranchId) REFERENCES CompanyBranch(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductImage()
    {
        string TableName = "ProductImage";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ProductId @NVARCHAR(40) @NOT_NULL,            -- Master

    Name @NVARCHAR(96) @NOT_NULL,

    ImageBlob @BLOB @NULL,

    IsDefault @BOOL default 0 @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,
    DisplayOrder int default 0 @NOT_NULL,

    Remarks @NBLOB_TEXT @NULL,

    FOREIGN KEY (ProductId) REFERENCES Product(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductAttribute()
    {
        string TableName = "ProductAttribute";
        string SqlText = $@"
CREATE TABLE {TableName} (
    Id @NVARCHAR(40) @NOT_NULL primary key,

    ProductId @NVARCHAR(40) @NOT_NULL,              -- Master
    ProductAttributeGroupId @NVARCHAR(40) @NULL,    -- Lookup

    Name @NVARCHAR(96) @NOT_NULL,
    TypeId int @NOT_NULL,                           -- Enum ProductAttributeType -- Text, Integer, Decimal, Option
    TextValue @NVARCHAR(512) @NOT_NULL,

    UnitOfMeasure @NVARCHAR(30) @NULL,

    DisplayOrder int default 0 @NOT_NULL,
    IsSpec @BOOL default 1 @NOT_NULL,
    IsFilter @BOOL default 0 @NOT_NULL,
    IsActive @BOOL default 1 @NOT_NULL,

    CONSTRAINT UQ_{TableName}_Product_Name UNIQUE (ProductId, Name),

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (ProductAttributeGroupId) REFERENCES ProductAttributeGroup(Id)
    )
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_ProductWarehouse()
    {
        string TableName = "ProductWarehouse";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    ProductId           @NVARCHAR(40) @NOT_NULL, -- Master

    WarehouseId         @NVARCHAR(40) @NOT_NULL, -- Lookup

    MinStock            @DECIMAL_(18, 4) @NULL,
    MaxStock            @DECIMAL_(18, 4) @NULL,
    ReorderPoint        @DECIMAL_(18, 4) @NULL,

    IsDefault           @BOOL default 0 @NOT_NULL,
    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo
 

    FOREIGN KEY (ProductId) REFERENCES Product(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_WarehouseLocation()
    {
        string TableName = "WarehouseLocation";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    WarehouseId         @NVARCHAR(40) @NOT_NULL, -- Master

    Code                @NVARCHAR(40) @NOT_NULL, -- Code LOC-XXXXXX
    Name                @NVARCHAR(96) @NOT_NULL,

    Zone                @NVARCHAR(40) @NULL,
    Aisle               @NVARCHAR(40) @NULL,
    Rack                @NVARCHAR(40) @NULL,
    Shelf               @NVARCHAR(40) @NULL,
    Bin                 @NVARCHAR(40) @NULL,

    IsActive            @BOOL default 1 @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo
 

    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id)
)
";
        Version.AddTable(SqlText);
    }
    void RegisterTable_BillOfMaterialLine()
    {
        string TableName = "BillOfMaterialLine";
        string SqlText = $@"
CREATE TABLE {TableName}
(
    Id                  @NVARCHAR(40) @NOT_NULL primary key,
    BillOfMaterialId    @NVARCHAR(40) @NOT_NULL, -- Master

    ProductId           @NVARCHAR(40) @NOT_NULL, -- Locator Product

    Quantity            @DECIMAL_(18, 4) @NOT_NULL,
    Notes               @NBLOB_TEXT @NULL,       -- LargeMemo 

    FOREIGN KEY (BillOfMaterialId) REFERENCES BillOfMaterial(Id),
    FOREIGN KEY (ProductId) REFERENCES Product(Id)
)
";
        Version.AddTable(SqlText);
    }
    void AddCodeProviderPatternStatements()
    {
        string SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'BillOfMaterial', 'BillOfMaterial', 'BOM-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'CashAccount', 'CashAccount', 'CASH-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'Company', 'Company', 'XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'FixedAsset', 'FixedAsset', 'AST-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'PersonAddress', 'PersonAddress', 'ADR-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'Product', 'Product', 'XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'Project', 'Project', 'YYYY-XXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'SalesPerson', 'SalesPerson', 'XXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'Warehouse', 'Warehouse', 'WH-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
        SqlText = $@"
INSERT INTO {DbConfig.SysNumberSeriesTableName}
(Id, Code, Name, Pattern, ResetPeriodId, NextNumber, LastResetValue, IsActive)
VALUES
('{MemTable.GenId()}', 'WarehouseLocation', 'WarehouseLocation', 'LOC-XXXXXX', 0, 1, NULL, 1)
";
        Version.AddStatementAfter(SqlText);
    }

    // ● protected
    protected override void RegisterInternal()
    {
        RegisterTable_SYS_LOG();
        RegisterTable_SYS_NUMBER_SERIES();
        RegisterTable_SYS_STR_RES();
        RegisterTable_SYS_APP_USER();
        RegisterTable_CustomerCategory();
        RegisterTable_SupplierCategory();
        RegisterTable_ProductBrand();
        RegisterTable_DiscountCategory();
        RegisterTable_UnitOfMeasure();
        RegisterTable_TaxOffice();
        RegisterTable_Bank();
        RegisterTable_ExpenseCategory();
        RegisterTable_PaymentMethod();
        RegisterTable_SalesPerson();
        RegisterTable_Carrier();
        RegisterTable_Country();
        RegisterTable_Currency();
        RegisterTable_VatRate();
        RegisterTable_PaymentTerm();
        RegisterTable_ProductGroup();
        RegisterTable_FiscalYear();
        RegisterTable_Language();
        RegisterTable_PersonRoleType();
        RegisterTable_StockReason();
        RegisterTable_ContactType();
        RegisterTable_AssetCategory();
        RegisterTable_AssetLocation();
        RegisterTable_AssetDepreciationMethod();
        RegisterTable_ProductDimension();
        RegisterTable_ProductAttributeGroup();
        RegisterTable_SYS_CONFIG();
        RegisterTable_PriceListType();
        RegisterTable_Company();
        RegisterTable_TaxCategory();
        RegisterTable_FiscalPeriod();
        RegisterTable_Person();
        RegisterTable_Category();
        RegisterTable_FixedAsset();
        RegisterTable_ProductDimensionValue();
        RegisterTable_CompanyBranch();
        RegisterTable_CompanyBankAccount();
        RegisterTable_PersonRole();
        RegisterTable_CostCenter();
        RegisterTable_Product();
        RegisterTable_PersonAddress();
        RegisterTable_PersonContact();
        RegisterTable_PersonBankAccount();
        RegisterTable_AssetAssignment();
        RegisterTable_AssetMaintenance();
        RegisterTable_AssetDocument();
        RegisterTable_AssetInsurance();
        RegisterTable_PriceList();
        RegisterTable_ProductGroups();
        RegisterTable_Warehouse();
        RegisterTable_Project();
        RegisterTable_ProductCategory();
        RegisterTable_ProductUnitOfMeasure();
        RegisterTable_ProductBarcode();
        RegisterTable_ProductSupplier();
        RegisterTable_BillOfMaterial();
        RegisterTable_CashAccount();
        RegisterTable_ProductImage();
        RegisterTable_ProductAttribute();
        RegisterTable_ProductWarehouse();
        RegisterTable_WarehouseLocation();
        RegisterTable_BillOfMaterialLine();
        AddCodeProviderPatternStatements();
    }

    // ● construction
    public SchemaVersion1()
    {
    }

    // ● properties
    public override int VersionNumber { get; } = 1;
}