<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);NU1510;NU1903</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Tripous\Tripous.csproj" />
        <ProjectReference Include="..\..\..\Tripous.Data\Tripous.Data.csproj" />
        <ProjectReference Include="..\..\..\Tripous.Logging\Tripous.Logging.csproj" />
        <ProjectReference Include="..\..\..\Tripous.Web\Tripous.Web.csproj" />
        <ProjectReference Include="..\tERP.Common\tERP.Common.csproj" />
        <ProjectReference Include="..\tERP.Data\tERP.Data.csproj" />
    </ItemGroup>

</Project>
