/*
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Common;

/// <summary>
/// Defines the financial statement category of an account.
/// </summary>
[TypeStore]
public enum AccountType
{
    /// <summary>No account type is specified.</summary>
    None = 0,

    /// <summary>
    /// Resources owned by the company.
    /// Examples: Cash, Bank, Customers, Inventory, Fixed Assets.
    /// </summary>
    Asset = 1,

    /// <summary>
    /// Obligations owed by the company.
    /// Examples: Suppliers, Loans, Taxes Payable.
    /// </summary>
    Liability = 2,

    /// <summary>
    /// Owners' equity.
    /// Examples: Share Capital, Retained Earnings.
    /// </summary>
    Equity = 3,

    /// <summary>
    /// Income generated by the company.
    /// Examples: Sales Revenue, Service Revenue.
    /// </summary>
    Revenue = 4,

    /// <summary>
    /// Costs and expenses incurred by the company.
    /// Examples: Purchases, Salaries, Rent, Utilities.
    /// </summary>
    Expense = 5,
}
