/*
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Common;

[TypeStore]
public enum AddressType
{
    None = 0,
    Main = 1,
    Billing = 2,
    Shipping = 3,
    Other = 4
}

[TypeStore]
public enum ProductType
{
    None = 0,
    Goods = 1,
    Service = 2,
    RawMaterial = 3
}

[TypeStore]
public enum ContactType
{
    None = 0,
    Person = 1,
    Accounting = 2,
    Sales = 3,
    Support = 4,
    Other = 5
}

[TypeStore]
public enum WarehouseType
{
    None = 0,
    Main = 1,
    Store = 2,
    Transit = 3,
    Production = 4,
    Scrap = 5,
    Virtual = 6,
}

[TypeStore]
public enum ProjectStatus
{
    None = 0,
    Draft = 1,
    Active = 2,
    Suspended = 3,
    Completed = 4,
    Cancelled = 5,
}

[TypeStore]
public enum ProductAttributeType
{
    None = 0,
    Text = 1, 
    Integer = 2, 
    Decimal = 3, 
    Option = 4,
}

[TypeStore]
public enum TradeType
{
    None = 0,
    Sales = 1,
    Purchases = 2,
    Warehouse = 3,
    Financial = 4,
    Accounting = 5,
}

[TypeStore]
public enum TradeStatus
{
    Draft = 0,
    Posted = 1,
    Cancelled = 2,
}

[TypeStore]
public enum TaxTreatment
{
    None = 0,
    Normal = 1,
    Exempt = 2,
    ThirdCountry = 3,
    IntraCommunity = 4,
}

[TypeStore]
public enum TradeLineType
{
    None = 0,
    Item = 1,
    Service = 2,
}

[TypeStore]
public enum StockCostingMethod
{
    None = 0,
    MovingAverage = 1,
    Fifo = 2,
    Lifo = 3,
    StandardCost = 4,
}

[TypeStore]
public enum AccountType
{
    None = 0,

    /// <summary>
    /// Resources owned by the company.
    /// Examples: Cash, Bank, Customers, Inventory, Fixed Assets.
    /// </summary>
    Asset = 1,

    /// <summary>
    /// Obligations owed by the company.
    /// Examples: Suppliers, Loans, Taxes Payable.
    /// </summary>
    Liability = 2,

    /// <summary>
    /// Owners' equity.
    /// Examples: Share Capital, Retained Earnings.
    /// </summary>
    Equity = 3,

    /// <summary>
    /// Income generated by the company.
    /// Examples: Sales Revenue, Service Revenue.
    /// </summary>
    Revenue = 4,

    /// <summary>
    /// Costs and expenses incurred by the company.
    /// Examples: Purchases, Salaries, Rent, Utilities.
    /// </summary>
    Expense = 5,
}

[TypeStore]
public enum NormalBalance
{
    None = 0,

    /// <summary>
    /// Debit-nature account.
    /// Typical for Assets and Expenses.
    /// </summary>
    Debit = 1,

    /// <summary>
    /// Credit-nature account.
    /// Typical for Liabilities, Equity and Revenue.
    /// </summary>
    Credit = 2,
}

[TypeStore]
public enum AssetStatus
{
    None = 0,
    Draft = 1,
    Active = 2,
    Disposed = 3,
    Sold = 4,
    Scrapped = 5,
}