/*
 * Tripous.Avalon
 * Copyright (c) Theo Bebekis
 *
 * Licensed under the Tripous License.
 * See License.txt for details.
 */

namespace tERP.Common;

[TypeStore]
public enum AddressType
{
    None = 0,
    Main = 1,
    Billing = 2,
    Shipping = 3,
    Other = 4
}

[TypeStore]
public enum ProductType
{
    None = 0,
    Goods = 1,
    Service = 2,
    RawMaterial = 3
}

[TypeStore]
public enum ContactType
{
    None = 0,
    Person = 1,
    Accounting = 2,
    Sales = 3,
    Support = 4,
    Other = 5
}

[TypeStore]
public enum WarehouseType
{
    None = 0,
    Main = 1,
    Store = 2,
    Transit = 3,
    Production = 4,
    Scrap = 5,
    Virtual = 6,
}

[TypeStore]
public enum ProjectStatus
{
    None = 0,
    Draft = 1,
    Active = 2,
    Suspended = 3,
    Completed = 4,
    Cancelled = 5,
}

[TypeStore]
public enum ProductAttributeType
{
    None = 0,
    Text = 1, 
    Integer = 2, 
    Decimal = 3, 
    Option = 4,
}

[TypeStore]
public enum TradeType
{
    None = 0,
    Sales = 1,
    Purchases = 2,
    Warehouse = 3,
    Financial = 4,
    Accounting = 5,
}

[TypeStore]
public enum TradeStatus
{
    Draft = 0,
    Posted = 1,
    Cancelled = 2,
}

/// <summary>
/// Defines the geographic level represented by a tax jurisdiction.
/// </summary>
[TypeStore]
public enum TaxJurisdictionType
{
    /// <summary>No jurisdiction type is specified.</summary>
    None = 0,
    /// <summary>A sovereign country.</summary>
    Country = 1,
    /// <summary>A state, province, or equivalent administrative region.</summary>
    State = 2,
    /// <summary>A county or equivalent subdivision of a state.</summary>
    County = 3,
    /// <summary>A city or municipality.</summary>
    City = 4,
    /// <summary>A special local tax authority or district.</summary>
    Special = 5,
    /// <summary>A tax territory containing multiple countries, such as the European Union.</summary>
    TaxZone = 6,
}

/// <summary>
/// Defines the family of indirect tax represented by a tax rate.
/// </summary>
[TypeStore]
public enum TaxType
{
    /// <summary>No indirect tax family is specified.</summary>
    None = 0,
    /// <summary>Value Added Tax, commonly used in Europe and many other countries.</summary>
    Vat = 1,
    /// <summary>Sales tax, commonly imposed by United States state and local authorities.</summary>
    SalesTax = 2,
    /// <summary>Goods and Services Tax, used in countries such as Canada and Australia.</summary>
    Gst = 3,
    /// <summary>Another indirect tax family not represented by the standard values.</summary>
    Other = 4,
}

/// <summary>
/// Defines how a tax rule calculates its monetary tax component.
/// </summary>
[TypeStore]
public enum TaxCalculationType
{
    /// <summary>No tax calculation method is specified.</summary>
    None = 0,
    /// <summary>Calculates tax as a percentage of the taxable amount.</summary>
    Percentage = 1,
    /// <summary>Calculates tax on the taxable amount including previously calculated tax components.</summary>
    TaxOnTax = 2,
}

/// <summary>
/// Legacy document tax treatment retained until the generated modules
/// and TradeDataModule are migrated to the tax rule model.
/// </summary>
[TypeStore]
public enum TaxTreatment
{
    None = 0,
    Normal = 1,
    Exempt = 2,
    ThirdCountry = 3,
    IntraCommunity = 4,
}

[TypeStore]
public enum TradeLineType
{
    None = 0,
    Item = 1,
    Service = 2,
}

[TypeStore]
public enum StockCostingMethod
{
    None = 0,
    MovingAverage = 1,
    Fifo = 2,
    Lifo = 3,
    StandardCost = 4,
}

[TypeStore]
public enum AccountType
{
    None = 0,

    /// <summary>
    /// Resources owned by the company.
    /// Examples: Cash, Bank, Customers, Inventory, Fixed Assets.
    /// </summary>
    Asset = 1,

    /// <summary>
    /// Obligations owed by the company.
    /// Examples: Suppliers, Loans, Taxes Payable.
    /// </summary>
    Liability = 2,

    /// <summary>
    /// Owners' equity.
    /// Examples: Share Capital, Retained Earnings.
    /// </summary>
    Equity = 3,

    /// <summary>
    /// Income generated by the company.
    /// Examples: Sales Revenue, Service Revenue.
    /// </summary>
    Revenue = 4,

    /// <summary>
    /// Costs and expenses incurred by the company.
    /// Examples: Purchases, Salaries, Rent, Utilities.
    /// </summary>
    Expense = 5,
}

[TypeStore]
public enum NormalBalance
{
    None = 0,

    /// <summary>
    /// Debit-nature account.
    /// Typical for Assets and Expenses.
    /// </summary>
    Debit = 1,

    /// <summary>
    /// Credit-nature account.
    /// Typical for Liabilities, Equity and Revenue.
    /// </summary>
    Credit = 2,
}

[TypeStore]
public enum AssetStatus
{
    None = 0,
    Draft = 1,
    Active = 2,
    Disposed = 3,
    Sold = 4,
    Scrapped = 5,
}

[TypeStore]
public enum DocumentAction
{
    None,
    Post
}